# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171116_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, help_text='Your fullname like first and last name, 512 characters.', max_length=512, null=True, verbose_name='fullname'),
        ),
    ]
