# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-17 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180509_1112'),
    ]

    operations = [
        migrations.RunSQL('CREATE UNIQUE INDEX account_user_email_unique_idx on account_user (LOWER(email));')
    ]
