# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 11:08
from __future__ import unicode_literals

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180517_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notification_frequency',
            field=common.fields.FixedTextField(choices=[(None, 'Disabled'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Every Two Weeks')], default='daily', null=True),
        ),
    ]
