# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 12:45
from __future__ import unicode_literals

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userprofile_notification_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notification_frequency',
            field=common.fields.FixedTextField(choices=[('', 'Disabled'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Every Two Weeks')], default='daily', null=True),
        ),
    ]
