# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180629_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accepted_tos',
            field=models.BooleanField(default=False),
        ),
    ]
