# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 07:35
from __future__ import unicode_literals

import common.database_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userprofile_accepted_tos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notification_frequency',
            field=common.database_fields.FixedTextField(choices=[('', 'Disabled'), ('1_daily', 'Daily'), ('2_weekly', 'Weekly'), ('3_biweekly', 'Every Two Weeks')], default='1_daily', null=True),
        ),
    ]
