version: '2.1'

services:
  proxy:
    image: unicef/unpp-proxy
    environment:
      - DJANGO_APPLICATION_SERVICE_HOST=backend
      - FRONTEND_SERVICE_HOST=frontend
    build:
      context: ./proxy
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
      - "8082:80"
    depends_on:
      - backend
      - frontend
    volumes_from:
      - backend

  backend:
    image: unicef/unpp-backend
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      args:
        ENV: dev
        REQUIREMENT_FILE: dev.pip
    volumes:
      - './backend:/code/'
      - '/data'
    command: bash -c "/usr/local/bin/wait-for-it.sh db:5432 -t 30 && python /code/manage.py collectstatic --noinput && python /code/manage.py migrate --noinput && python /code/manage.py sanctions_list_sync --initial && gunicorn unpp_api.wsgi -c /code/gunicorn_config.py"
    depends_on:
      - db

  db:
    image: unicef/unpp-db
    env_file:
      - .env
    build:
      context: ./db
      dockerfile: ./Dockerfile
    ports:
      - "8081:5432"

  frontend:
    image: unicef/unpp-frontend
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
        ENV: dev
    volumes:
        - ./frontend/:/code
        - /code/node_modules
    command: bash -c "yarn run start"
