version: '2.1'

services:
  proxy:
    image: unicef/unpp-proxy
    environment:
      - DJANGO_APPLICATION_SERVICE_HOST=backend
      - FRONTEND_SERVICE_HOST=frontend
    build:
      context: ./proxy
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
      - "8082:80"
    depends_on:
      - backend
      - frontend
    volumes_from:
      - backend

  redis:
    restart: always
    image: redis:4.0.11-alpine3.8

  backend:
    image: unicef/unpp-backend
    env_file:
      - .env
    environment:
      - REDIS_INSTANCE=redis:6379
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      args:
        ENV: dev
        REQUIREMENT_FILE: dev.pip
    volumes:
      - './backend:/code/'
      - '/data'
    depends_on:
      - db
      - redis

  db:
    image: postgres:9.5.15-alpine
    env_file:
      - .env

  legacy_db:
    image: microsoft/mssql-server-linux:latest
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=y
    ports:
      - "1433:1433"
    command: bash -c "apt-get update && apt-get install -y curl && /opt/mssql/bin/sqlservr"
    volumes:
        - ~/Desktop/:/Desktop

  frontend:
    image: unicef/unpp-frontend
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
        ENV: dev
    volumes:
        - ./frontend/:/code
        - /code/node_modules
    command: bash -c "yarn run start"
