version: '2.1'

services:
  proxy:
    image: unicef/unpp-proxy
    environment:
      - DJANGO_APPLICATION_SERVICE_HOST=backend
    build:
      context: ./proxy
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend

  backend:
    image: unicef/unpp-backend
    env_file:
      - backend/.env
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      args:
        ENV: dev
        REQUIREMENT_FILE: dev.pip
    volumes:
      - './backend:/code/'
    command: bash -c "/usr/local/bin/waitforit -host=db -port=5432 && python /code/manage.py migrate && python /code/manage.py collectstatic --noinput && uwsgi --ini /code/unpp_api/uwsgi.ini"
    depends_on:
      - db

  db:
    image: unicef/unpp-db
    build:
      context: ./db
      dockerfile: ./Dockerfile

  frontend:
    image: unicef/unpp-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
        - ./frontend/:/code
        - /code/node_modules
    command: bash -c "yarn run build && node server.js"
