# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.CharField(default='US', max_length=2),
            preserve_default=False,
        ),
    ]
