# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20171011_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file_field', models.FileField(upload_to=b'')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
