# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20171013_0238'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adminlevel1',
            unique_together=set([('name', 'country_code')]),
        ),
    ]
