# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20180122_1313'),
        ('common', '0008_auto_20180123_1101'),
    ]

    operations = [
    ]
