# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-07 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_merge_20180123_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonfile',
            name='file_field',
            field=models.FileField(upload_to=''),
        ),
    ]
