# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 07:15
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20180507_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))], verbose_name='Latitude'),
        ),
    ]
