# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 09:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_auto_20180718_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonfile',
            name='file_field',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(('pdf', 'jpg', 'doc', 'tiff', 'png'))]),
        ),
    ]
