# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencymember',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='agencyoffice',
            options={'ordering': ['id']},
        ),
    ]
