# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-07 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_auto_20180123_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyprofile',
            name='eoi_template',
            field=models.FileField(upload_to=''),
        ),
    ]
