# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-09 11:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import common.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0008_auto_20180507_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencymember',
            name='role',
        ),
        migrations.AlterUniqueTogether(
            name='agencymember',
            unique_together=set([('user', 'office')]),
        ),
        migrations.AddField(
            model_name='agencymember',
            name='role',
            field=common.fields.FixedTextField(choices=[('HQ_EDITOR', 'HQ Editor'), ('ADMINISTRATOR', 'Administrator'), ('READER', 'Reader'), ('EDITOR_BASIC', 'Basic Editor'), ('EDITOR_ADVANCED', 'Advanced Editor'), ('EDITOR_BASIC_PAM', 'Basic Editor (PAM USER)'), ('EDITOR_ADVANCED_MFT', 'Advanced Editor (MFT USER)')], default='READER'),
        ),
    ]
