# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-16 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_auto_20180509_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencymember',
            name='status',
        ),
    ]
