# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-16 12:27
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


def set_my_defaults(apps, schema_editor):
    AgencyOffice = apps.get_model('agency', 'AgencyOffice')
    for office in AgencyOffice.objects.all().iterator():
        country_code = office.countries_code[0]
        office.country = country_code
        office.save()


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_remove_agencymember_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyoffice',
            name='country',
            field=django_countries.fields.CountryField(null=True, max_length=2),
            preserve_default=False,
        ),
        migrations.RunPython(set_my_defaults),
        migrations.AlterField(
            model_name='agencyoffice',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.RemoveField(
            model_name='agencyoffice',
            name='countries_code',
        ),
        migrations.RemoveField(
            model_name='agencyoffice',
            name='name',
        ),
        migrations.AlterUniqueTogether(
            name='agencyoffice',
            unique_together=set([('agency', 'country')]),
        ),
    ]
