# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_auto_20180522_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
