# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 09:26
from __future__ import unicode_literals

from django.db import migrations


def migrate_legacy_agency_roles(apps, schema_editor):
    AgencyMember = apps.get_model('agency', 'AgencyMember')

    # mapping is not straightforward for agency, so just reset to default
    AgencyMember.objects.filter(role__iexact='Adm').update(role='READER')
    AgencyMember.objects.filter(role__iexact='Edi').update(role='READER')
    AgencyMember.objects.filter(role__iexact='Rea').update(role='READER')


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_auto_20180612_0625'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_agency_roles)
    ]
