# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 03:40
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_unsolicited', models.BooleanField(default=False, verbose_name='Is unsolicited?')),
                ('cn', models.FileField(upload_to=b'')),
                ('status', models.CharField(choices=[('Pen', 'Pending'), ('Pre', 'Preselected'), ('Rej', 'Rejected')], default='Pen', max_length=3)),
                ('did_win', models.BooleanField(default=False, verbose_name='Did win?')),
                ('did_accept', models.BooleanField(default=False, verbose_name='Did accept?')),
                ('ds_justification_select', models.TextField()),
                ('ds_justification_reason', models.TextField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='agency.Agency')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('feedback', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_feedbacks', to='project.Application')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_reviews', to='project.Application')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationReviewCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('score', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('application_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_review_criterias', to='project.ApplicationReview')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('score', models.PositiveIntegerField()),
                ('date_reviewed', models.DateField(verbose_name='Date reviewed')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='project.Application')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('scale', models.CharField(choices=[('Low', '1-3'), ('Std', '1-10'), ('Hig', '1-100')], default='Std', max_length=3)),
                ('weight', models.PositiveSmallIntegerField(default=100, help_text='Value in percentage, provide number from 0 to 100', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Weight in percentage')),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EOI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('display_type', models.CharField(choices=[('Ope', 'Open'), ('Dir', 'Direct')], default='Ope', max_length=3)),
                ('is_closed', models.BooleanField(default=True, verbose_name='Is closed?')),
                ('title', models.CharField(max_length=255)),
                ('cn_template', models.FileField(upload_to=b'')),
                ('description', models.CharField(max_length=200, verbose_name='Brief background of the project')),
                ('other_information', models.CharField(max_length=200, verbose_name='Other information (optional)')),
                ('start_date', models.DateField(verbose_name='Estimated Start Date')),
                ('end_date', models.DateField(verbose_name='Estimated End Date')),
                ('deadline_date', models.DateField(verbose_name='Estimated Deadline Date')),
                ('notif_results_date', models.DateField(verbose_name='Notification of Results Date')),
                ('has_weighting', models.BooleanField(default=True, verbose_name='Has weighting?')),
                ('closed_justification', models.TextField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressions_of_interest', to='agency.Agency')),
                ('agency_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressions_of_interest', to='agency.AgencyOffice')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressions_of_interest', to='common.Country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressions_of_interest', to=settings.AUTH_USER_MODEL)),
                ('focal_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressions_of_interest_by_focal_point', to=settings.AUTH_USER_MODEL)),
                ('invited_partners', models.ManyToManyField(related_name='expressions_of_interest', to='partner.Partner')),
                ('locations', models.ManyToManyField(related_name='expressions_of_interest', to='common.Point')),
                ('reviewers', models.ManyToManyField(related_name='expressions_of_interest_by_reviewers', to=settings.AUTH_USER_MODEL)),
                ('specializations', models.ManyToManyField(related_name='expressions_of_interest', to='common.Specialization')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='assessmentcriteria',
            name='eoi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments_criteria', to='project.EOI'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='project.AssessmentCriteria'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationreviewcriteria',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_review_criterias', to='project.AssessmentCriteria'),
        ),
        migrations.AddField(
            model_name='application',
            name='eoi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='project.EOI'),
        ),
        migrations.AddField(
            model_name='application',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='partner.Partner'),
        ),
        migrations.AddField(
            model_name='application',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
