# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoi',
            name='closed_justification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
