# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_eoi_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eoi',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='eoi',
            name='status',
        ),
    ]
