# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 03:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20170807_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationreview',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicationreview',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='applicationreviewcriteria',
            name='application_review',
        ),
        migrations.RemoveField(
            model_name='applicationreviewcriteria',
            name='criteria',
        ),
        migrations.AddField(
            model_name='eoi',
            name='status',
            field=models.CharField(choices=[('Ope', 'Open'), ('Clo', 'Closed')], default='Ope', max_length=3),
        ),
        migrations.AlterField(
            model_name='application',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='agency.Agency'),
        ),
        migrations.AlterField(
            model_name='application',
            name='eoi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='project.EOI'),
        ),
        migrations.AlterField(
            model_name='eoi',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='Estimated Deadline Date'),
        ),
        migrations.AlterField(
            model_name='eoi',
            name='notif_results_date',
            field=models.DateField(blank=True, null=True, verbose_name='Notification of Results Date'),
        ),
        migrations.AlterField(
            model_name='eoi',
            name='reviewers',
            field=models.ManyToManyField(related_name='expressions_of_interest_as_reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ApplicationReview',
        ),
        migrations.DeleteModel(
            name='ApplicationReviewCriteria',
        ),
    ]
