# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_pin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pin',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='eoi',
            name='other_information',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Other information (optional)'),
        ),
    ]
