# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 06:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20170821_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='eoi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='project.EOI'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='partner.Partner'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pinned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to=settings.AUTH_USER_MODEL),
        ),
    ]
