# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20170822_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentcriteria',
            name='display_type',
            field=models.CharField(choices=[('SEE', 'Sector expertise and experience'), ('Pro', 'Project management'), ('LEP', 'Local experience and presence'), ('Con', 'Contribution of resource'), ('Cos', 'Cost effectiveness'), ('Exp', 'Experience working with UN'), ('Rel', 'Relevance of proposal to achieving expected results'), ('Cla', 'Clarity of activities and expected results'), ('Inn', 'Innovative approach'), ('Sus', 'Sustainability of intervention'), ('Rea', 'Realistic timelines and plans'), ('ASC', 'Access/security considerations'), ('Oth', 'Other')], default='SEE', max_length=3),
        ),
    ]
