# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_auto_20170814_0841'),
        ('project', '0006_assessmentcriteria_display_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eoi',
            name='selected_partners',
            field=models.ManyToManyField(related_name='eoi_as_selected_partners', to='partner.Partner'),
        ),
        migrations.AlterField(
            model_name='eoi',
            name='status',
            field=models.CharField(choices=[('Ope', 'Open'), ('Clo', 'Closed/Under Review'), ('Com', 'Completed')], default='Ope', max_length=3),
        ),
    ]
