# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20170905_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='eoi',
            name='justification_for_direct_selection',
            field=models.CharField(blank=True, choices=[('Kno', 'Known expertise'), ('Loc', 'Local presence'), ('Inn', 'Innovative approach'), ('TCC', 'Time constraints/criticality of response'), ('Imp', 'Importance of strengthening national civil society engagement'), ('Oth', 'Other')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='eoi',
            name='summary_justification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
