# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20170905_0520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eoi',
            name='justification_for_direct_selection',
        ),
        migrations.RemoveField(
            model_name='eoi',
            name='summary_justification',
        ),
        migrations.AddField(
            model_name='eoi',
            name='selected_source',
            field=models.CharField(choices=[('CSO', 'CSO-Initiated'), ('UNI', 'UN-Initiated')], default='CSO', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eoi',
            name='selected_partners',
            field=models.ManyToManyField(related_name='expressions_of_interest', to='partner.PartnerSelected'),
        ),
    ]
