# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20170905_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoi',
            name='selected_source',
            field=models.CharField(blank=True, choices=[('CSO', 'CSO-Initiated'), ('UNI', 'UN-Initiated')], max_length=3, null=True),
        ),
    ]
