# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20170905_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoi',
            name='selected_partners',
            field=models.ManyToManyField(blank=True, related_name='expressions_of_interest', to='partner.PartnerSelected'),
        ),
    ]
