# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 05:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20170905_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ds_justification_select',
            field=models.CharField(blank=True, choices=[('Kno', 'Known expertise'), ('Loc', 'Local presence'), ('Inn', 'Innovative approach'), ('TCC', 'Time constraints/criticality of response'), ('Imp', 'Importance of strengthening national civil society engagement'), ('Oth', 'Other')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='eoi',
            name='cn_template',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='eoi',
            name='invited_partners',
            field=models.ManyToManyField(blank=True, null=True, related_name='expressions_of_interest', to='partner.Partner'),
        ),
        migrations.AlterField(
            model_name='eoi',
            name='reviewers',
            field=models.ManyToManyField(blank=True, null=True, related_name='eoi_as_reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
