# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20170908_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eoi',
            name='selected_partners',
        ),
    ]
