# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0015_auto_20170912_0844'),
        ('project', '0014_auto_20170912_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ds_justification_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set([('eoi', 'partner')]),
        ),
    ]
