# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20170914_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='agency',
        ),
    ]
