# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_remove_application_agency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='ds_justification_reason',
            new_name='justification_reason',
        ),
    ]
