# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20170915_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cn_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
