# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_application_cn_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eoi',
            name='goal',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Goal, Objective, Expected Outcome and Results.'),
        ),
    ]
