# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 03:00
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_auto_20170919_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ds_justification_select',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Kno', 'Known expertise'), ('Loc', 'Local presence'), ('Inn', 'Innovative approach'), ('TCC', 'Time constraints/criticality of response'), ('Imp', 'Importance of strengthening national civil society engagement'), ('Oth', 'Other')], max_length=3), default=list, null=True, size=None),
        ),
    ]
