# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 06:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20170927_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='scores',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[{'score': 0, 'selection_criteria': None}]),
        ),
    ]
