# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 23:23
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0019_auto_20170929_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentcriteria',
            name='description',
        ),
        migrations.RemoveField(
            model_name='assessmentcriteria',
            name='display_type',
        ),
        migrations.RemoveField(
            model_name='assessmentcriteria',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='assessmentcriteria',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='assessmentcriteria',
            name='weight',
        ),
        migrations.AddField(
            model_name='assessment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='scores',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[{'score': 0, 'selection_criteria': None}]),
        ),
        migrations.AddField(
            model_name='assessmentcriteria',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'selection_criteria': '', 'weight': 0}),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='date_reviewed',
            field=models.DateField(auto_now=True, verbose_name='Date reviewed'),
        ),
        migrations.AlterField(
            model_name='assessmentcriteria',
            name='eoi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessments_criteria', to='project.EOI'),
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='score',
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together=set([('reviewer', 'application')]),
        ),
    ]
