# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 03:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20170929_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='proposal_of_eoi_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'agency_id': None, 'locations': [], 'specializations': [], 'title': ''}),
        ),
    ]
