# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_assessmentcriteria_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cn_id',
        ),
    ]
