# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 03:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_application_proposal_of_eoi_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentcriteria',
            name='eoi',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='criteria',
        ),
        migrations.AddField(
            model_name='eoi',
            name='assessments_criteria',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'selection_criteria': '', 'weight': 0}),
        ),
        migrations.DeleteModel(
            name='AssessmentCriteria',
        ),
    ]
