# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_remove_application_cn_id'),
        ('project', '0022_auto_20170919_0751'),
    ]

    operations = [
    ]
