# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 05:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_auto_20171011_0329'),
        ('project', '0024_auto_20171011_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='agency.Agency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='proposal_of_eoi_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'country_code': None, 'locations': [], 'specializations': [], 'title': ''}),
        ),
    ]
