# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 02:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_commonfile'),
        ('project', '0025_auto_20171012_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='did_withdraw',
            field=models.BooleanField(default=False, verbose_name='Did accept?'),
        ),
        migrations.AddField(
            model_name='application',
            name='locations_proposal_of_eoi',
            field=models.ManyToManyField(related_name='applications', to='common.Point'),
        ),
        migrations.AddField(
            model_name='application',
            name='withdraw_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='proposal_of_eoi_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'specializations': [], 'title': ''}),
        ),
    ]
