# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_auto_20171013_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eoi',
            name='country_code',
        ),
    ]
