# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_remove_eoi_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='locations_proposal_of_eoi',
            field=models.ManyToManyField(blank=True, related_name='applications', to='common.Point'),
        ),
    ]
