# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_auto_20171013_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='did_decline',
            field=models.BooleanField(default=False, verbose_name='Did decline?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='did_withdraw',
            field=models.BooleanField(default=False, verbose_name='Did withdraw?'),
        ),
    ]
