# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_eoi_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='eoi_converted',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unsolicited_conversion', to='project.EOI'),
        ),
    ]
