# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20171013_0238'),
        ('project', '0031_application_eoi_converted'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cn_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concept_notes', to='common.CommonFile'),
        ),
    ]
