# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_remove_application_cn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='cn_fk',
            new_name='cn',
        ),
    ]
