# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0031_auto_20171031_0715'),
        ('project', '0036_auto_20171027_0634'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pin',
            unique_together=set([('eoi', 'partner')]),
        ),
    ]
