# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_auto_20171031_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='did_accept_date',
            new_name='decision_date',
        ),
    ]
