# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_auto_20171107_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eoi',
            name='status',
        ),
        migrations.AddField(
            model_name='eoi',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
