# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_auto_20171114_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoi',
            name='selected_source',
            field=models.CharField(blank=True, choices=[('UCN', 'Unsolicited Concept Note'), ('UNI', 'UN-Initiated')], max_length=3, null=True),
        ),
    ]
