# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_auto_20171117_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoi',
            name='completed_reason',
            field=models.CharField(blank=True, choices=[('Par', 'Finalized - Partner accepted'), ('Can', 'Finalized - CFEI canceled'), ('NoC', 'Finalized - No successful applicant')], max_length=3, null=True),
        ),
    ]
