# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 03:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import project.validators


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_auto_20171123_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoi',
            name='assessments_criteria',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'selection_criteria': '', 'weight': 0}, validators=[project.validators.validate_weight_adjustments]),
        ),
    ]
