# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_auto_20171123_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoi',
            name='description',
            field=models.CharField(max_length=5000, verbose_name='Brief background of the project'),
        ),
        migrations.AlterField(
            model_name='eoi',
            name='goal',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Goal, Objective, Expected Outcome and Results.'),
        ),
        migrations.AlterField(
            model_name='eoi',
            name='other_information',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Other information (optional)'),
        ),
    ]
