# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 09:41
from __future__ import unicode_literals

from django.db import migrations


def archive_assessments_from_removed_reviewers(apps, schema_editor):
    Assessment = apps.get_model('project', 'Assessment')

    for assessment in Assessment.objects.filter(archived=False):
        if assessment.application.eoi and not assessment.application.eoi.reviewers.filter(
                id=assessment.reviewer_id).exists():
            assessment.archived = True
            assessment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0044_auto_20180126_1325'),
    ]

    operations = [
        migrations.RunPython(archive_assessments_from_removed_reviewers)
    ]
