# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-07 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_auto_20180207_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoi',
            name='cn_template',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
