# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-21 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0046_auto_20180507_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='eoi',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether CFEI is a draft or has been published'),
        ),
    ]
