# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-25 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0047_eoi_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_published',
            field=models.NullBooleanField(help_text='Whether application is a draft or has been published (applicable to UCN)'),
        ),
    ]
