# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20180507_1034'),
        ('project', '0048_application_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ds_attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ds_applications', to='common.CommonFile'),
        ),
    ]
