# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 08:57
from __future__ import unicode_literals

import common.database_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0049_application_ds_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='eoi',
            name='completed_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eoi',
            name='completed_retention',
            field=models.CharField(blank=True, choices=[('1YR', 'For one year'), ('2YR', 'For second year'), ('3YR', 'For a third year'), ('4YR', 'For a fourth year')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='eoi',
            name='completed_reason',
            field=common.database_fields.FixedTextField(blank=True, choices=[('partners', 'Finalized - Partner accepted'), ('cancelled', 'Finalized - Cancelled'), ('no_candidate', 'Finalized - No successful applicant')], null=True),
        ),
    ]
