# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 10:32
from __future__ import unicode_literals

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0051_auto_20180530_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoi',
            name='completed_reason',
            field=common.fields.FixedTextField(blank=True, choices=[('partners', 'Finalized - Partner accepted'), ('no_candidate', 'Finalized - No successful applicant'), ('cancelled', 'Finalized - Cancelled'), ('accepted', 'Finalized - Partner accepted direct selection'), ('accepted_retention', 'Finalized - Partner accepted retention. Maintain decision for:')], null=True),
        ),
        migrations.AlterField(
            model_name='eoi',
            name='completed_retention',
            field=models.CharField(blank=True, choices=[('1YR', 'one year'), ('2YR', 'second year'), ('3YR', 'a third year'), ('4YR', 'a fourth year')], max_length=3, null=True),
        ),
    ]
