# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 12:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import project.validators


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0054_eoi_published_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoi',
            name='assessments_criteria',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, validators=[project.validators.validate_weight_adjustments]),
        ),
    ]
