# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 07:34
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0055_auto_20180608_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ds_justification_select',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Kno', 'Known expertise'), ('Loc', 'Local presence'), ('Inn', 'Innovative approach'), ('TCC', 'Time constraints/criticality of response'), ('Imp', 'Importance of strengthening national civil society engagement'), ('Ret', 'Partner retention'), ('Oth', 'Other')], max_length=3), blank=True, default=list, null=True, size=None),
        ),
    ]
