# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0056_auto_20180614_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='published_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
