# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 11:04
from __future__ import unicode_literals

import common.database_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0058_auto_20180621_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoi',
            name='completed_reason',
            field=common.database_fields.FixedTextField(blank=True, choices=[('partners', 'Finalized - Partner accepted'), ('no_candidate', 'Finalized - No successful applicant'), ('cancelled', 'Finalized - Cancelled'), ('accepted_retention', 'Finalized - Partner accepted retention. Maintain decision for:'), ('accepted', 'Finalized - Partner accepted direct selection')], null=True),
        ),
    ]
