# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-13 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0059_auto_20180625_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoi',
            name='display_type',
            field=models.CharField(choices=[('Ope', 'Open'), ('Dir', 'Direct')], default='Ope', max_length=3, verbose_name='Type of Call'),
        ),
    ]
