# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0060_auto_20180713_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoi',
            name='display_type',
            field=models.CharField(choices=[('Ope', 'Open Selection'), ('Dir', 'Direct Selection / Retention')], default='Ope', max_length=3, verbose_name='Type of Call'),
        ),
    ]
