# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0063_auto_20180803_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_a_committee_score',
            field=models.BooleanField(default=False, help_text='If only one reviewer is selected, indicate that they are providing scores on behalf of a committee.'),
        ),
    ]
