# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 11:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0012_auto_20180724_0902'),
        ('project', '0064_assessment_is_a_committee_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='EOIAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.TextField(max_length=5120)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eoi_attachments', to=settings.AUTH_USER_MODEL)),
                ('eoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='project.EOI')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eoi_attachments', to='common.CommonFile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
