# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-09 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0068_auto_20180809_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='eoi',
            name='sent_for_decision',
            field=models.BooleanField(default=False, help_text='Whether CFEI has been forwarded to focal point to select a partner.'),
        ),
        migrations.AlterField(
            model_name='eoi',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether CFEI is a draft or has been published.'),
        ),
        migrations.AlterField(
            model_name='eoi',
            name='sent_for_publishing',
            field=models.BooleanField(default=False, help_text='Whether CFEI has been forwarded to focal point to be published.'),
        ),
    ]
