# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-14 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0071_auto_20180810_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='eoi',
            name='clarification_request_deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='Clarification Request Date'),
        ),
    ]
