# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-14 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0012_auto_20180724_0902'),
        ('project', '0072_eoi_clarification_request_deadline_date'),
        ('partner', '0073_partnercollaborationevidence_editable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClarificationRequestAnswerFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.TextField(max_length=1024)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eoi_question_answers', to=settings.AUTH_USER_MODEL)),
                ('eoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='project.EOI')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eoi_question_answers', to='common.CommonFile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClarificationRequestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('question', models.TextField(max_length=5120)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eoi_questions', to=settings.AUTH_USER_MODEL)),
                ('eoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='project.EOI')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eoi_questions', to='partner.Partner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
