# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-23 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0073_clarificationrequestanswerfile_clarificationrequestquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clarificationrequestanswerfile',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='clarificationrequestquestion',
            options={'ordering': ('id',)},
        ),
    ]
