# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 06:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0075_eoi_clarification_request_deadline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoi',
            name='displayID',
            field=models.TextField(editable=False, max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
