# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0076_auto_20180927_0613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eoi',
            options={'ordering': ('-created',), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
