# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0079_eoi_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoi',
            name='display_type',
            field=models.CharField(choices=[('Ope', 'Open Selection'), ('Dir', 'Direct Selection / Retention'), ('Ucn', 'Unsolicited Concept Note')], default='Ope', max_length=3, verbose_name='Type of Call'),
        ),
    ]
