# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-22 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20171031_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='notifieduser',
            options={'ordering': ['created']},
        ),
    ]
