# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 11:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0003_auto_20180122_1313'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notifieduser',
            unique_together=set([('notification', 'recipient')]),
        ),
    ]
