# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20180606_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifieduser',
            name='sent_as_email',
            field=models.BooleanField(default=False),
        ),
    ]
