---
kind: Service
apiVersion: v1
metadata:
  name: db
spec:
  selector:
    app: db-container
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-container
  template:
    metadata:
      labels:
        app: db-container
    spec:
      containers:
        - name: db
          image: unicef/unpp-db
          ports:
            - containerPort: 5432
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: db-volume-{{ENV}}
      volumes:
      - name: db-volume-{{ENV}}
        persistentVolumeClaim:
          claimName: db-volume-claim-{{ENV}}
      }
      }
