---
kind: Service
apiVersion: v1
metadata:
    name: db
    namespace: {{NAMESPACE}}
spec:
    selector:
        app: db-container
    ports:
        -   protocol: TCP
            port: 5432
            targetPort: 5432
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: db
    labels:
        app: db
    namespace: {{NAMESPACE}}
spec:
    replicas: 1
    selector:
        matchLabels:
            app: db-container
    template:
        metadata:
            labels:
                app: db-container
        spec:
            containers:
                -   name: db
                    image: postgres:9.5.15-alpine
                    ports:
                        -   containerPort: 5432
                    volumeMounts:
                        -   mountPath: /var/lib/postgresql/data
                            name: db-volume-{{NAMESPACE}}
            volumes:
                -   name: db-volume-{{NAMESPACE}}
                    persistentVolumeClaim:
                        claimName: db-volume-claim-{{NAMESPACE}}
