---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: send-daily-notifications
  annotations:
    revision: "{{CF_SHORT_REVISION}}"
  namespace: {{NAMESPACE}}
spec:
  schedule: "* 12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backend-cronjobs-container
            image: unicef/unpp-backend:{{CF_SHORT_REVISION}}
            command: ["bash"]
            args: ["-c", "python /code/manage.py send_daily_notifications"]
            env:
                - name: SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: secret-key
                      key: password
                - name: ENV
                  value: {{ENV}}
                - name: POSTGRES_DB
                  value: {{POSTGRES_DB}}
                - name: POSTGRES_USER
                  value: {{POSTGRES_USER}}
                - name: POSTGRES_HOST
                  value: {{POSTGRES_HOST}}
                - name: DJANGO_ALLOWED_HOST
                  value: {{DJANGO_ALLOWED_HOST}}
          restartPolicy: OnFailure
