---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: send-daily-notifications
  annotations:
    revision: "{{CF_SHORT_REVISION}}"
  namespace: {{NAMESPACE}}
spec:
  schedule: "* 12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backend-cronjobs-container
            image: unicef/unpp-backend:{{CF_SHORT_REVISION}}
            command: ["bash"]
            args: ["-c", "python /code/manage.py send_daily_notifications"]
            env:
                - name: SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: secret-key
                      key: password
                - name: ENV
                  value: {{ENV}}
                - name: POSTGRES_DB
                  value: {{POSTGRES_DB}}
                - name: POSTGRES_USER
                  value: {{POSTGRES_USER}}
                - name: POSTGRES_HOST
                  value: {{POSTGRES_HOST}}
                - name: DJANGO_ALLOWED_HOST
                  value: {{DJANGO_ALLOWED_HOST}}
                - name: EMAIL_HOST
                  value: "{{EMAIL_HOST}}"
                - name: EMAIL_PORT
                  value: "{{EMAIL_PORT}}"
                - name: EMAIL_HOST_USER
                  value: "{{EMAIL_HOST_USER}}"
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: send-clarification-deadline-passed-notifications
  annotations:
    revision: "{{CF_SHORT_REVISION}}"
  namespace: {{NAMESPACE}}
spec:
  schedule: "* 12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backend-cronjobs-container
            image: unicef/unpp-backend:{{CF_SHORT_REVISION}}
            command: ["bash"]
            args: ["-c", "python /code/manage.py send_clarification_deadline_passed_notifications"]
            env:
                - name: SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: secret-key
                      key: password
                - name: ENV
                  value: {{ENV}}
                - name: POSTGRES_DB
                  value: {{POSTGRES_DB}}
                - name: POSTGRES_USER
                  value: {{POSTGRES_USER}}
                - name: POSTGRES_HOST
                  value: {{POSTGRES_HOST}}
                - name: DJANGO_ALLOWED_HOST
                  value: {{DJANGO_ALLOWED_HOST}}
                - name: EMAIL_HOST
                  value: "{{EMAIL_HOST}}"
                - name: EMAIL_PORT
                  value: "{{EMAIL_PORT}}"
                - name: EMAIL_HOST_USER
                  value: "{{EMAIL_HOST_USER}}"
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: send-weekly-notifications
  annotations:
    revision: "{{CF_SHORT_REVISION}}"
  namespace: {{NAMESPACE}}
spec:
  schedule: "* 12 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backend-cronjobs-container
            image: unicef/unpp-backend:{{CF_SHORT_REVISION}}
            command: ["bash"]
            args: ["-c", "python /code/manage.py send_weekly_notifications"]
            env:
                - name: SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: secret-key
                      key: password
                - name: ENV
                  value: {{ENV}}
                - name: POSTGRES_DB
                  value: {{POSTGRES_DB}}
                - name: POSTGRES_USER
                  value: {{POSTGRES_USER}}
                - name: POSTGRES_HOST
                  value: {{POSTGRES_HOST}}
                - name: DJANGO_ALLOWED_HOST
                  value: {{DJANGO_ALLOWED_HOST}}
                - name: EMAIL_HOST
                  value: "{{EMAIL_HOST}}"
                - name: EMAIL_PORT
                  value: "{{EMAIL_PORT}}"
                - name: EMAIL_HOST_USER
                  value: "{{EMAIL_HOST_USER}}"
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sanction-list-sync-and-rescan
  annotations:
    revision: "{{CF_SHORT_REVISION}}"
  namespace: {{NAMESPACE}}
spec:
  schedule: "* 12 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backend-cronjobs-container
            image: unicef/unpp-backend:{{CF_SHORT_REVISION}}
            command: ["bash"]
            args: ["-c", "python /code/manage.py sanction_sync_and_rescan"]
            env:
                - name: SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: secret-key
                      key: password
                - name: ENV
                  value: {{ENV}}
                - name: POSTGRES_DB
                  value: {{POSTGRES_DB}}
                - name: POSTGRES_USER
                  value: {{POSTGRES_USER}}
                - name: POSTGRES_HOST
                  value: {{POSTGRES_HOST}}
                - name: EMAIL_HOST
                  value: "{{EMAIL_HOST}}"
                - name: EMAIL_PORT
                  value: "{{EMAIL_PORT}}"
                - name: EMAIL_HOST_USER
                  value: "{{EMAIL_HOST_USER}}"
                - name: DJANGO_ALLOWED_HOST
                  value: {{DJANGO_ALLOWED_HOST}}
          restartPolicy: OnFailure

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sync-unicef-erp-data
  annotations:
    revision: "{{CF_SHORT_REVISION}}"
  namespace: {{NAMESPACE}}
spec:
  schedule: "0 12 28-31 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backend-cronjobs-container
            image: unicef/unpp-backend:{{CF_SHORT_REVISION}}
            command: ["bash"]
            args: ["-c", "python /code/manage.py sync_unicef_erp_data"]
            env:
                - name: SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: secret-key
                      key: password
                - name: ENV
                  value: {{ENV}}
                - name: POSTGRES_DB
                  value: {{POSTGRES_DB}}
                - name: POSTGRES_USER
                  value: {{POSTGRES_USER}}
                - name: POSTGRES_HOST
                  value: {{POSTGRES_HOST}}
                - name: DJANGO_ALLOWED_HOST
                  value: {{DJANGO_ALLOWED_HOST}}
                - name: EMAIL_HOST
                  value: "{{EMAIL_HOST}}"
                - name: EMAIL_PORT
                  value: "{{EMAIL_PORT}}"
                - name: EMAIL_HOST_USER
                  value: "{{EMAIL_HOST_USER}}"
                - name: UNICEF_PARTNER_DETAILS_URL
                  value: "{{UNICEF_PARTNER_DETAILS_URL}}"
                - name: UNICEF_API_USERNAME
                  value: "{{UNICEF_API_USERNAME}}"
                - name: UNICEF_API_PASSWORD
                  value: "{{UNICEF_API_PASSWORD}}"
          restartPolicy: OnFailure
