apiVersion: batch/v1
kind: Job
metadata:
  name: backend-fakedata-migration
  annotations:
    revision: "{{CF_SHORT_REVISION}}"
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      containers:
      - name: backend-fakedata
        image: unicef/unpp-backend:{{CF_SHORT_REVISION}}
        command: ["bash"]
        args: ["-c", "python /code/manage.py migrate && python /code/manage.py loaddata --app common initial.json && python /code/manage.py fakedata 50 --clean_before"]
        env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: unpp-staging-secrets
                  key: SECRET_KEY
           - name: ENV
              value: {{ENV}}
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: unpp-staging-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: unpp-staging-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: unpp-staging-secrets
                  key: POSTGRES_HOST
            - name: DJANGO_ALLOWED_HOST
              value: {{DJANGO_ALLOWED_HOST}}
      restartPolicy: Never
  backoffLimit: 4