---
apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migration
  annotations:
    revision: "{{CF_SHORT_REVISION}}"
  labels:
    redeploy: "true" 
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      containers:
      - name: backend-migration-container
        image: unicef/unpp-backend:{{CF_SHORT_REVISION}}
        command: ["bash"]
        args: ["-c", "python /code/manage.py migrate --noinput"]
        env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: password
            - name: ENV
              value: {{ENV}}
            - name: POSTGRES_DB
              value: {{POSTGRES_DB}}
            - name: POSTGRES_USER
              value: {{POSTGRES_USER}}
            - name: POSTGRES_HOST
              value: {{POSTGRES_HOST}}
            - name: DJANGO_ALLOWED_HOST
              value: {{DJANGO_ALLOWED_HOST}}

      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: batch/v1
kind: Job
metadata:
  name: backend-collectstatic
  annotations:
    revision: "{{CF_SHORT_REVISION}}"
  labels:
    redeploy: "true"
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      containers:
      - name: backend-collectstatic-container
        image: unicef/unpp-backend:{{CF_SHORT_REVISION}}
        command: ["bash"]
        args: ["-c", "python /code/manage.py collectstatic --noinput"]
        volumeMounts:
          - name: static-volume-{{NAMESPACE}}
            mountPath: /data
        env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: password
            - name: ENV
              value: {{ENV}}
            - name: POSTGRES_DB
              value: {{POSTGRES_DB}}
            - name: POSTGRES_USER
              value: {{POSTGRES_USER}}
            - name: POSTGRES_HOST
              value: {{POSTGRES_HOST}}
            - name: DJANGO_ALLOWED_HOST
              value: {{DJANGO_ALLOWED_HOST}}
      volumes:
      - name: static-volume-{{NAMESPACE}}
        persistentVolumeClaim:
          claimName: static-volume-claim-{{NAMESPACE}}
      restartPolicy: Never
  backoffLimit: 4
