# -*- coding: utf-8 -*-
from __future__ import unicode_literals

COUNTRIES_ALPHA2_CODE = (
    ("AF", "Afghanistan"),
    ("AL", "Albania"),
    ("DZ", "Algeria"),
    ("AR", "Argentina"),
    ("AM", "Armenia"),
    ("AZ", "Azerbaijan"),
    ("AI", "Anguilla"),
    ("AG", "Antigua and Barbuda"),
    ("BB", "Barbados"),
    ("VG", "Virgin Islands (UK)"),
    ("DM", "Dominica"),
    ("GD", "Grenada"),
    ("MS", "Montserrat"),
    ("KN", "Saint Kitts and Nevis"),
    ("LC", "Saint Lucia"),
    ("VC", "Saint Vincent and the Grenadines"),
    ("TC", "Turks & Caicos"),
    ("TT", "Trinidad and Tobago"),
    ("BT", "Bhutan"),
    ("BO", "Bolivia"),
    ("BW", "Botswana"),
    ("BA", "Bosnia and Herzegovina"),
    ("BR", "Brazil"),
    ("BG", "Bulgaria"),
    ("MM", "Myanmar"),
    ("BI", "Burundi"),
    ("BY", "Belarus"),
    ("KH", "Cambodia"),
    ("CM", "Cameroon"),
    ("CF", "Central African Republic"),
    ("LK", "Sri Lanka"),
    ("TD", "Chad"),
    ("CL", "Chile"),
    ("CN", "China"),
    ("CO", "Colombia"),
    ("CD", "Congo, Dem. Rep."),
    ("CR", "Costa Rica"),
    ("HR", "Croatia"),
    ("CU", "Cuba"),
    ("BJ", "Benin"),
    ("DK", "Denmark"),
    ("DO", "Dominican Republic"),
    ("EC", "Ecuador"),
    ("SV", "El Salvador"),
    ("GQ", "Equatorial Guinea"),
    ("ET", "Ethiopia"),
    ("ER", "Eritrea"),
    ("AS", "American Samoa"),
    ("CK", "Cook Islands"),
    ("FJ", "Fiji"),
    ("KI", "Kiribati"),
    ("MH", "Marshall Islands"),
    ("FM", "Micronesia"),
    ("NR", "Nauru"),
    ("NU", "Niue"),
    ("PW", "Palau, Republic Of"),
    ("WS", "Samoa"),
    ("SB", "Solomon Islands"),
    ("TK", "Tokelau"),
    ("TO", "Tonga"),
    ("TV", "Tuvalu"),
    ("VU", "Vanuatu"),
    ("GA", "Gabon"),
    ("GM", "Gambia"),
    ("GE", "Georgia"),
    ("GH", "Ghana"),
    ("GT", "Guatemala"),
    ("GN", "Guinea"),
    ("GY", "Guyana"),
    ("SR", "Suriname"),
    ("HT", "Haiti"),
    ("HN", "Honduras"),
    ("IN", "India"),
    ("ID", "Indonesia"),
    ("IR", "Iran"),
    ("IQ", "Iraq"),
    ("CI", "Cote D'Ivoire"),
    ("JM", "Jamaica"),
    ("JO", "Jordan"),
    ("KZ", "Kazakhstan"),
    ("KE", "Kenya"),
    ("KG", "Kyrgyzstan"),
    ("LA", "Lao, People's Dem. Rep"),
    ("LB", "Lebanon"),
    ("LS", "Lesotho"),
    ("LR", "Liberia"),
    ("LY", "Libya"),
    ("MK", "Macedonia, TFYR"),
    ("MG", "Madagascar"),
    ("MW", "Malawi"),
    ("MY", "Malaysia"),
    ("MV", "Maldives"),
    ("ML", "Mali"),
    ("MR", "Mauritania"),
    ("MX", "Mexico"),
    ("MN", "Mongolia"),
    ("MA", "Morocco"),
    ("NP", "Nepal"),
    ("NI", "Nicaragua"),
    ("NE", "Niger"),
    ("NG", "Nigeria"),
    ("PK", "Pakistan"),
    ("PA", "Panama"),
    ("PY", "Paraguay"),
    ("CG", "Congo"),
    ("PE", "Peru"),
    ("PH", "Philippines"),
    ("RO", "Romania"),
    ("RU", "Russian Federation"),
    ("RW", "Rwanda"),
    ("BH", "Bahrain"),
    ("KW", "Kuwait"),
    ("QA", "Qatar"),
    ("SA", "Saudi Arabia"),
    ("AE", "United Arab Emirates"),
    ("SN", "Senegal"),
    ("SL", "Sierra Leone"),
    ("SO", "Somalia"),
    ("ZA", "South Africa"),
    ("SD", "Sudan"),
    ("SZ", "Swaziland"),
    ("SS", "South Sudan"),
    ("SY", "Syrian Arab Republic"),
    ("TJ", "Tajikistan"),
    ("TH", "Thailand"),
    ("TG", "Togo"),
    ("TN", "Tunisia"),
    ("TR", "Turkey"),
    ("TM", "Turkmenistan"),
    ("UG", "Uganda"),
    ("UA", "Ukraine"),
    ("EG", "Egypt"),
    ("TZ", "Tanzania, United Rep. of"),
    ("BF", "Burkina Faso"),
    ("UY", "Uruguay"),
    ("UZ", "Uzbekistan"),
    ("VE", "Venezuela"),
    ("YE", "Yemen"),
    ("ZM", "Zambia"),
    ("BD", "Bangladesh"),
    ("KP", "Korea, Democratic People's Republic of"),
    ("VN", "Viet Nam"),
    ("MD", "Moldova"),
    ("CH", "Switzerland"),
    ("BZ", "Belize"),
    ("ZW", "Zimbabwe"),
    ("OM", "Oman"),
    ("PG", "Papua New Guinea"),
    ("KM", "Comoros"),
    ("DJ", "Djibouti"),
    ("AO", "Angola"),
    ("CV", "Cabo Verde"),
    ("ST", "Sao Tome and Principe"),
    ("GW", "Guinea-Bissau"),
    ("MZ", "Mozambique"),
    ("NA", "Namibia"),
    ("PS", "Palestine"),
    ("TL", "Timor-Leste"),
    ("ME", "Montenegro"),
    ("RS", "Serbia"),
    ("AW", "Aruba"),
    ("AU", "Australia"),
    ("AT", "Austria"),
    ("BE", "Belgium"),
    ("BM", "Bermuda"),
    ("BS", "Bahamas"),
    ("BN", "Brunei"),
    ("CA", "Canada"),
    ("KY", "Cayman Islands"),
    ("CZ", "Czech Republic"),
    ("CY", "Cyprus"),
    ("EE", "Estonia"),
    ("FI", "Finland"),
    ("FR", "France"),
    ("DE", "Germany"),
    ("GI", "Gibraltar"),
    ("GR", "Greece"),
    ("GU", "Guam"),
    ("HU", "Hungary"),
    ("IS", "Iceland"),
    ("IE", "Ireland"),
    ("IL", "Israel"),
    ("IT", "Italy"),
    ("JP", "Japan"),
    ("LV", "Latvia"),
    ("LT", "Lithuania"),
    ("LU", "Luxembourg"),
    ("MU", "Mauritius"),
    ("MT", "Malta"),
    ("MC", "Monaco"),
    ("NC", "New Caledonia"),
    ("NL", "Netherlands"),
    ("NO", "Norway"),
    ("NZ", "New Zealand"),
    ("PL", "Poland"),
    ("PT", "Portugal"),
    ("PR", "Puerto Rico"),
    ("KR", "Korea, Republic of"),
    ("SC", "Seychelles"),
    ("SG", "Singapore"),
    ("SK", "Slovakia"),
    ("ES", "Spain"),
    ("SI", "Slovenia"),
    ("SE", "Sweden"),
    ("GB", "United Kingdom"),
    ("US", "United States of America"),
    ("VI", "Virgin Islands (USA)"),
    ("AD", "Andorra"),
    ("GF", "French Guiana"),
    ("PF", "French Polynesia (France)"),
    ("GL", "Greenland"),
    ("GP", "Guadeloupe"),
    ("LI", "Liechtenstein"),
    ("MQ", "Martinique"),
    ("AN", "Netherlands Antilles"),
    ("MP", "Northern Mariana Islands"),
    ("RE", "Reunion"),
    ("SH", "Saint Helena"),
    ("SM", "San Marino"),
    ("CS", "Serbia & Montenegro"),
    ("VA", "Vatican City"),
    ("WF", "Wallis & Futuna Islands"),
)

COUNTRIES_ALPHA2_CODE_DICT = dict(COUNTRIES_ALPHA2_CODE)

LOCATION_OPTIONAL_COUNTRIES = [
    'PS'
]
