# data volume for backend
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: static-volume-{{NAMESPACE}}
  labels:
    type: local
  namespace: {{NAMESPACE}}
spec:
  capacity:
    storage: 4Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data-{{NAMESPACE}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: static-volume-claim-{{NAMESPACE}}
  labels:
    type: local
  namespace: {{NAMESPACE}}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

# postgres volume
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: db-volume-{{NAMESPACE}}
  labels:
    type: local
  namespace: {{NAMESPACE}}
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /db-{{NAMESPACE}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-volume-claim-{{NAMESPACE}}
  labels:
    type: local
  namespace: {{NAMESPACE}}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
