# data volume for backend
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: static-volume-prod
  labels:
    type: local
spec:
  capacity:
    storage: 4Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data-prod
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: static-volume-claim-prod
  labels:
    type: local
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

# postgres volume
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: db-volume-prod
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /db-prod
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-volume-claim-prod
  labels:
    type: local
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi