---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  annotations:
    revision: "{{CF_SHORT_REVISION}}"
  namespace: {{NAMESPACE}}
spec:
  ports:
  - protocol: TCP
    port: 8080
  type: NodePort
  selector:
    app: frontend-container
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
  annotations:
    revision: "{{CF_SHORT_REVISION}}"
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-container
  template:
    metadata:
      labels:
        app: frontend-container
    spec:
      containers:
        - name: frontend
          image: unicef/unpp-frontend:{{CF_SHORT_REVISION}}
          command: ["bash"]
          args: ["-c", "nginx -g \"daemon off;\""]
          env:
            - name: MAP_BOX_KEY
              value: {{MAP_BOX_KEY}}
          volumeMounts:
            - name: srv-www
              mountPath: /srv/www/
      initContainers:
        - name: compile-frontend
          image: unicef/unpp-frontend:{{CF_SHORT_REVISION}}
          command: ["bash"]
          args: ["-c", "/.compile-production.sh"]
          env:
            - name: MAP_BOX_KEY
              value: {{MAP_BOX_KEY}}
          volumeMounts:
            - name: srv-www
              mountPath: /srv/www/
      volumes:
        - name: srv-www
          emptyDir: {}
