apiVersion: batch/v1
kind: Job
metadata:
  name: frontend-build
  annotations:
    revision: "{{CF_SHORT_REVISION}}"
  labels:
    redeploy: "true"
  namespace: {{NAMESPACE}}
spec:
  template:
    spec:
      containers:
      - name: frontend-build-container
        image: unicef/unpp-frontend:{{CF_SHORT_REVISION}}
        command: ["bash"]
        args: ["-c", "yarn run build"]
        volumeMounts:
          - name: frontend-volume-{{NAMESPACE}}
            mountPath: /code/build
        env:
          - name: MAP_BOX_KEY
            value: {{MAP_BOX_KEY}}

      volumes:
      - name: frontend-volume-{{NAMESPACE}}
        persistentVolumeClaim:
          claimName: frontend-volume-claim-{{NAMESPACE}}
      restartPolicy: Never
  backoffLimit: 4
