export const INIT_COUNTRY_ID = -1;

const initialState = {
  columns: [
    { name: 'name', title: 'Organization\'s Legal Name' },
    { name: 'acronym', title: 'Acronym' },
    { name: 'type', title: 'Type of Organization' },
    { name: 'country', title: 'Country' },
    { name: 'experience', title: 'Experience working with UN' },
  ],
  partners: [
    { id: 1,
      name: 'Partner 0',
      acronym: 'ATCHQ',
      type: 'International NGO (INGO)',
      country: 'Kenya',
      experience: 'UNICEF',
      details: {
        mail: 'partner10@email.org',
        phone: '001 444 444 444',
        website: 'www.partner10.com',
        headName: 'John Smith',
        headTitle: 'Mr',
        headEmail: 'john.smith@email.org',
        languages: 'English, German, Polish, French',
        sectors: [
          { name: 'Education', area: 'Education in emergencies, Learning outcomes' },
          { name: 'Food security', area: 'Agricultural inputs' },
          { name: 'Health', area: 'Health in emergencies, Maternal and new born health' },
        ],
      },
    },
    { id: 2,
      name: 'Partner 1',
      acronym: 'BGOP',
      type: 'International NGO (INGO)',
      country: 'England',
      experience: 'WFP',
      details: {
        mail: 'partner10@email.org',
        phone: '001 444 444 444',
        website: 'www.partner10.com',
        headName: 'John Smith',
        headTitle: 'Mr',
        headEmail: 'john.smith@email.org',
        languages: 'English, German, Polish, French',
        sectors: [
          { name: 'Education', area: 'Education in emergencies, Learning outcomes' },
          { name: 'Food security', area: 'Agricultural inputs' },
          { name: 'Health', area: 'Health in emergencies, Maternal and new born health' },
        ],
      } },
    { id: 3,
      name: 'Partner 3',
      acronym: 'ATGQ',
      type: 'National NGO',
      country: 'Poland',
      experience: 'WFP',
      details: {
        mail: 'partner10@email.org',
        phone: '001 444 444 444',
        website: 'www.partner10.com',
        headName: 'John Smith',
        headTitle: 'Mr',
        headEmail: 'john.smith@email.org',
        languages: 'English, German, Polish, French',
        sectors: [
          { name: 'Education', area: 'Education in emergencies, Learning outcomes' },
          { name: 'Food security', area: 'Agricultural inputs' },
          { name: 'Health', area: 'Health in emergencies, Maternal and new born health' },
        ],
      } },
    { id: 4,
      name: 'Partner 4',
      acronym: 'QEW',
      type: 'Academic Institution',
      country: 'France',
      experience: 'UNICEF',
      details: {
        mail: 'partner10@email.org',
        phone: '001 444 444 444',
        website: 'www.partner10.com',
        headName: 'John Smith',
        headTitle: 'Mr',
        headEmail: 'john.smith@email.org',
        languages: 'English, German, Polish, French',
        sectors: [
          { name: 'Education', area: 'Education in emergencies, Learning outcomes' },
          { name: 'Food security', area: 'Agricultural inputs' },
          { name: 'Health', area: 'Health in emergencies, Maternal and new born health' },
        ],
      } },
    { id: 5,
      name: 'Partner 0',
      acronym: 'ATCHQ',
      type: 'International NGO (INGO)',
      country: 'Kenya',
      experience: 'UNICEF',
      details: {
        mail: 'partner10@email.org',
        phone: '001 444 444 444',
        website: 'www.partner10.com',
        headName: 'John Smith',
        headTitle: 'Mr',
        headEmail: 'john.smith@email.org',
        languages: 'English, German, Polish, French',
        sectors: [
          { name: 'Education', area: 'Education in emergencies, Learning outcomes' },
          { name: 'Food security', area: 'Agricultural inputs' },
          { name: 'Health', area: 'Health in emergencies, Maternal and new born health' },
        ],
      } },
    { id: 6,
      name: 'Partner 1',
      acronym: 'BGOP',
      type: 'International NGO (INGO)',
      country: 'England',
      experience: 'WFP',
      details: {
        mail: 'partner10@email.org',
        phone: '001 444 444 444',
        website: 'www.partner10.com',
        headName: 'John Smith',
        headTitle: 'Mr',
        headEmail: 'john.smith@email.org',
        languages: 'English, German, Polish, French',
        sectors: [
          { name: 'Education', area: 'Education in emergencies, Learning outcomes' },
          { name: 'Food security', area: 'Agricultural inputs' },
          { name: 'Health', area: 'Health in emergencies, Maternal and new born health' },
        ],
      } },
    { id: 7,
      name: 'Partner 3',
      acronym: 'ATGQ',
      type: 'National NGO',
      country: 'Poland',
      experience: 'WFP',
      details: {
        mail: 'partner10@email.org',
        phone: '001 444 444 444',
        website: 'www.partner10.com',
        headName: 'John Smith',
        headTitle: 'Mr',
        headEmail: 'john.smith@email.org',
        languages: 'English, German, Polish, French',
        sectors: [
          { name: 'Education', area: 'Education in emergencies, Learning outcomes' },
          { name: 'Food security', area: 'Agricultural inputs' },
          { name: 'Health', area: 'Health in emergencies, Maternal and new born health' },
        ],
      } },
    { id: 8,
      name: 'Partner 4',
      acronym: 'QEW',
      type: 'Academic Institution',
      country: 'France',
      experience: 'UNICEF',
      details: {
        mail: 'partner10@email.org',
        phone: '001 444 444 444',
        website: 'www.partner10.com',
        headName: 'John Smith',
        headTitle: 'Mr',
        headEmail: 'john.smith@email.org',
        languages: 'English, German, Polish, French',
        sectors: [
          { name: 'Education', area: 'Education in emergencies, Learning outcomes' },
          { name: 'Food security', area: 'Agricultural inputs' },
          { name: 'Health', area: 'Health in emergencies, Maternal and new born health' },
        ],
      } },
    { id: 9,
      name: 'Partner 0',
      acronym: 'ATCHQ',
      type: 'International NGO (INGO)',
      country: 'Kenya',
      experience: 'UNICEF',
      details: {
        mail: 'partner10@email.org',
        phone: '001 444 444 444',
        website: 'www.partner10.com',
        headName: 'John Smith',
        headTitle: 'Mr',
        headEmail: 'john.smith@email.org',
        languages: 'English, German, Polish, French',
        sectors: [
          { name: 'Education', area: 'Education in emergencies, Learning outcomes' },
          { name: 'Food security', area: 'Agricultural inputs' },
          { name: 'Health', area: 'Health in emergencies, Maternal and new born health' },
        ],
      } },
    { id: 10,
      name: 'Partner 1',
      acronym: 'BGOP',
      type: 'International NGO (INGO)',
      country: 'England',
      experience: 'WFP',
      details: {
        mail: 'partner10@email.org',
        phone: '001 444 444 444',
        website: 'www.partner10.com',
        headName: 'John Smith',
        headTitle: 'Mr',
        headEmail: 'john.smith@email.org',
        languages: 'English, German, Polish, French',
        sectors: [
          { name: 'Education', area: 'Education in emergencies, Learning outcomes' },
          { name: 'Food security', area: 'Agricultural inputs' },
          { name: 'Health', area: 'Health in emergencies, Maternal and new born health' },
        ],
      } },
    { id: 11,
      name: 'Partner 3',
      acronym: 'ATGQ',
      type: 'National NGO',
      country: 'Poland',
      experience: 'WFP',
      details: {
        mail: 'partner10@email.org',
        phone: '001 444 444 444',
        website: 'www.partner10.com',
        headName: 'John Smith',
        headTitle: 'Mr',
        headEmail: 'john.smith@email.org',
        languages: 'English, German, Polish, French',
        sectors: [
          { name: 'Education', area: 'Education in emergencies, Learning outcomes' },
          { name: 'Food security', area: 'Agricultural inputs' },
          { name: 'Health', area: 'Health in emergencies, Maternal and new born health' },
        ],
      } },
    { id: 12,
      name: 'Partner 4',
      acronym: 'QEW',
      type: 'Academic Institution',
      country: 'France',
      experience: 'UNICEF',
      details: {
        mail: 'partner10@email.org',
        phone: '001 444 444 444',
        website: 'www.partner10.com',
        headName: 'John Smith',
        headTitle: 'Mr',
        headEmail: 'john.smith@email.org',
        languages: 'English, German, Polish, French',
        sectors: [
          { name: 'Education', area: 'Education in emergencies, Learning outcomes' },
          { name: 'Food security', area: 'Agricultural inputs' },
          { name: 'Health', area: 'Health in emergencies, Maternal and new born health' },
        ],
      } },
    { id: 13,
      name: 'Partner 0',
      acronym: 'ATCHQ',
      type: 'International NGO (INGO)',
      country: 'Kenya',
      experience: 'UNICEF',
      details: {
        mail: 'partner10@email.org',
        phone: '001 444 444 444',
        website: 'www.partner10.com',
        headName: 'John Smith',
        headTitle: 'Mr',
        headEmail: 'john.smith@email.org',
        languages: 'English, German, Polish, French',
        sectors: [
          { name: 'Education', area: 'Education in emergencies, Learning outcomes' },
          { name: 'Food security', area: 'Agricultural inputs' },
          { name: 'Health', area: 'Health in emergencies, Maternal and new born health' },
        ],
      } },
    { id: 14,
      name: 'Partner 1',
      acronym: 'BGOP',
      type: 'International NGO (INGO)',
      country: 'England',
      experience: 'WFP',
      details: {
        mail: 'partner10@email.org',
        phone: '001 444 444 444',
        website: 'www.partner10.com',
        headName: 'John Smith',
        headTitle: 'Mr',
        headEmail: 'john.smith@email.org',
        languages: 'English, German, Polish, French',
        sectors: [
          { name: 'Education', area: 'Education in emergencies, Learning outcomes' },
          { name: 'Food security', area: 'Agricultural inputs' },
          { name: 'Health', area: 'Health in emergencies, Maternal and new born health' },
        ],
      } },
    { id: 15,
      name: 'Partner 3',
      acronym: 'ATGQ',
      type: 'National NGO',
      country: 'Poland',
      experience: 'WFP',
      details: {
        mail: 'partner10@email.org',
        phone: '001 444 444 444',
        website: 'www.partner10.com',
        headName: 'John Smith',
        headTitle: 'Mr',
        headEmail: 'john.smith@email.org',
        languages: 'English, German, Polish, French',
        sectors: [
          { name: 'Education', area: 'Education in emergencies, Learning outcomes' },
          { name: 'Food security', area: 'Agricultural inputs' },
          { name: 'Health', area: 'Health in emergencies, Maternal and new born health' },
        ],
      } },
    { id: 16,
      name: 'Partner 4',
      acronym: 'QEW',
      type: 'Academic Institution',
      country: 'France',
      experience: 'UNICEF',
      details: {
        mail: 'partner10@email.org',
        phone: '001 444 444 444',
        website: 'www.partner10.com',
        headName: 'John Smith',
        headTitle: 'Mr',
        headEmail: 'john.smith@email.org',
        languages: 'English, German, Polish, French',
        sectors: [
          { name: 'Education', area: 'Education in emergencies, Learning outcomes' },
          { name: 'Food security', area: 'Agricultural inputs' },
          { name: 'Health', area: 'Health in emergencies, Maternal and new born health' },
        ],
      } },
    { id: 16,
      name: 'Partner 4',
      acronym: 'QEW',
      type: 'Academic Institution',
      country: 'France',
      experience: 'UNICEF',
      details: {
        mail: 'partner10@email.org',
        phone: '001 444 444 444',
        website: 'www.partner10.com',
        headName: 'John Smith',
        headTitle: 'Mr',
        headEmail: 'john.smith@email.org',
        languages: 'English, German, Polish, French',
        sectors: [
          { name: 'Education', area: 'Education in emergencies, Learning outcomes' },
          { name: 'Food security', area: 'Agricultural inputs' },
          { name: 'Health', area: 'Health in emergencies, Maternal and new born health' },
        ],
      } },
    { id: 16,
      name: 'Partner 4',
      acronym: 'QEW',
      type: 'Academic Institution',
      country: 'France',
      experience: 'UNICEF',
      details: {
        mail: 'partner10@email.org',
        phone: '001 444 444 444',
        website: 'www.partner10.com',
        headName: 'John Smith',
        headTitle: 'Mr',
        headEmail: 'john.smith@email.org',
        languages: 'English, German, Polish, French',
        sectors: [
          { name: 'Education', area: 'Education in emergencies, Learning outcomes' },
          { name: 'Food security', area: 'Agricultural inputs' },
          { name: 'Health', area: 'Health in emergencies, Maternal and new born health' },
        ],
      } },
    { id: 17,
      name: 'Partner 0',
      acronym: 'ATCHQ',
      type: 'International NGO (INGO)',
      country: 'Kenya',
      experience: 'UNICEF',
      details: {
        mail: 'partner10@email.org',
        phone: '001 444 444 444',
        website: 'www.partner10.com',
        headName: 'John Smith',
        headTitle: 'Mr',
        headEmail: 'john.smith@email.org',
        languages: 'English, German, Polish, French',
        sectors: [
          { name: 'Education', area: 'Education in emergencies, Learning outcomes' },
          { name: 'Food security', area: 'Agricultural inputs' },
          { name: 'Health', area: 'Health in emergencies, Maternal and new born health' },
        ],
      } },
    { id: 18,
      name: 'Partner 0',
      acronym: 'ATCHQ',
      type: 'International NGO (INGO)',
      country: 'Kenya',
      experience: 'UNICEF',
      details: {
        mail: 'partner10@email.org',
        phone: '001 444 444 444',
        website: 'www.partner10.com',
        headName: 'John Smith',
        headTitle: 'Mr',
        headEmail: 'john.smith@email.org',
        languages: 'English, German, Polish, French',
        sectors: [
          { name: 'Education', area: 'Education in emergencies, Learning outcomes' },
          { name: 'Food security', area: 'Agricultural inputs' },
          { name: 'Health', area: 'Health in emergencies, Maternal and new born health' },
        ],
      } },
    { id: 19,
      name: 'Partner 0',
      acronym: 'ATCHQ',
      type: 'International NGO (INGO)',
      country: 'Kenya',
      experience: 'UNICEF',
      details: {
        mail: 'partner10@email.org',
        phone: '001 444 444 444',
        website: 'www.partner10.com',
        headName: 'John Smith',
        headTitle: 'Mr',
        headEmail: 'john.smith@email.org',
        languages: 'English, German, Polish, French',
        sectors: [
          { name: 'Education', area: 'Education in emergencies, Learning outcomes' },
          { name: 'Food security', area: 'Agricultural inputs' },
          { name: 'Health', area: 'Health in emergencies, Maternal and new born health' },
        ],
      } },
    { id: 20,
      name: 'Partner 0',
      acronym: 'ATCHQ',
      type: 'International NGO (INGO)',
      country: 'Kenya',
      experience: 'UNICEF',
      details: {
        mail: 'partner10@email.org',
        phone: '001 444 444 444',
        website: 'www.partner10.com',
        headName: 'John Smith',
        headTitle: 'Mr',
        headEmail: 'john.smith@email.org',
        languages: 'English, German, Polish, French',
        sectors: [
          { name: 'Education', area: 'Education in emergencies, Learning outcomes' },
          { name: 'Food security', area: 'Agricultural inputs' },
          { name: 'Health', area: 'Health in emergencies, Maternal and new born health' },
        ],
      } },
  ],
};

export default function agencyPartnersListReducer(state = initialState, action) {
  switch (action.type) {
    default:
      return state;
  }
}
