export const INIT_COUNTRY_ID = -1;

const initialState = {
  columns: [
    { name: 'id', title: 'ID' },
    { name: 'project_title', title: 'Project Title', width: 200 },
    { name: 'cfei_id', title: 'CFEI ID' },
    { name: 'agency', title: 'Agency' },
    { name: 'country', title: 'Country' },
    { name: 'sector', title: 'Sector' },
    { name: 'date', title: 'Application Date' },
    { name: 'status', title: 'Status' },
  ],
  notes: [
    { id: 'CN/0192',
      name: 'Partner 0',
      project_title: 'Capacity building for small rural farmers',
      cfei_id: '123/FF2',
      agency: 'UNICEF',
      country: 'Kenya',
      sector: 'Food Security',
      date: '30 Sep 2017',
      status: 'Pending',
    },
    { id: 'CN/0190',
      name: 'Partner 0',
      project_title: 'Teaching students new language',
      cfei_id: '21/AA/2',
      agency: 'WFP',
      country: 'Spain',
      sector: 'Education',
      date: '1 Oct 2017',
      status: 'Offer Made',
    },
    { id: 'CN/603',
      name: 'Partner 0',
      project_title: 'Capacity building for small rural farmers',
      cfei_id: '123/FF2',
      agency: 'UNICEF',
      country: 'England',
      sector: 'Food Security',
      date: '30 Sep 2017',
      status: 'Offer Accepted',
    },
    { id: 'CN/0132',
      name: 'Partner 0',
      project_title: 'Capacity building for small rural farmers',
      cfei_id: '13/FA2',
      agency: 'UNICEF',
      country: 'Poland',
      sector: 'Food Security',
      date: '30 Sep 2017',
      status: 'Offer Declined',
    },
    { id: 'CN/0192',
      name: 'Partner 0',
      project_title: 'Capacity building for small rural farmers',
      cfei_id: '123/FF2',
      agency: 'UNICEF',
      country: 'Kenya',
      sector: 'Food Security',
      date: '30 Sep 2017',
      status: 'Pending',
    },
    { id: 'CN/0190',
      name: 'Partner 0',
      project_title: 'Teaching students new language',
      cfei_id: '21/AA/2',
      agency: 'WFP',
      country: 'Spain',
      sector: 'Education',
      date: '1 Oct 2017',
      status: 'Offer Made',
    },
    { id: 'CN/603',
      name: 'Partner 0',
      project_title: 'Capacity building for small rural farmers',
      cfei_id: '123/FF2',
      agency: 'UNICEF',
      country: 'England',
      sector: 'Food Security',
      date: '30 Sep 2017',
      status: 'Offer Accepted',
    },
    { id: 'CN/0132',
      name: 'Partner 0',
      project_title: 'Capacity building for small rural farmers',
      cfei_id: '13/FA2',
      agency: 'UNICEF',
      country: 'Poland',
      sector: 'Food Security',
      date: '30 Sep 2017',
      status: 'Offer Declined',
    }, { id: 'CN/0192',
      name: 'Partner 0',
      project_title: 'Capacity building for small rural farmers',
      cfei_id: '123/FF2',
      agency: 'UNICEF',
      country: 'Kenya',
      sector: 'Food Security',
      date: '30 Sep 2017',
      status: 'Pending',
    },
    { id: 'CN/0190',
      name: 'Partner 0',
      project_title: 'Teaching students new language',
      cfei_id: '21/AA/2',
      agency: 'WFP',
      country: 'Spain',
      sector: 'Education',
      date: '1 Oct 2017',
      status: 'Offer Made',
    },
    { id: 'CN/603',
      name: 'Partner 0',
      project_title: 'Capacity building for small rural farmers',
      cfei_id: '123/FF2',
      agency: 'UNICEF',
      country: 'England',
      sector: 'Food Security',
      date: '30 Sep 2017',
      status: 'Offer Accepted',
    },
    { id: 'CN/0132',
      name: 'Partner 0',
      project_title: 'Capacity building for small rural farmers',
      cfei_id: '13/FA2',
      agency: 'UNICEF',
      country: 'Poland',
      sector: 'Food Security',
      date: '30 Sep 2017',
      status: 'Offer Declined',
    }, { id: 'CN/0192',
      name: 'Partner 0',
      project_title: 'Capacity building for small rural farmers',
      cfei_id: '123/FF2',
      agency: 'UNICEF',
      country: 'Kenya',
      sector: 'Food Security',
      date: '30 Sep 2017',
      status: 'Pending',
    },
    { id: 'CN/0190',
      name: 'Partner 0',
      project_title: 'Teaching students new language',
      cfei_id: '21/AA/2',
      agency: 'WFP',
      country: 'Spain',
      sector: 'Education',
      date: '1 Oct 2017',
      status: 'Offer Made',
    },
    { id: 'CN/603',
      name: 'Partner 0',
      project_title: 'Capacity building for small rural farmers',
      cfei_id: '123/FF2',
      agency: 'UNICEF',
      country: 'England',
      sector: 'Food Security',
      date: '30 Sep 2017',
      status: 'Offer Accepted',
    },
    { id: 'CN/0132',
      name: 'Partner 0',
      project_title: 'Capacity building for small rural farmers',
      cfei_id: '13/FA2',
      agency: 'UNICEF',
      country: 'Poland',
      sector: 'Food Security',
      date: '30 Sep 2017',
      status: 'Offer Declined',
    }, { id: 'CN/0192',
      name: 'Partner 0',
      project_title: 'Capacity building for small rural farmers',
      cfei_id: '123/FF2',
      agency: 'UNICEF',
      country: 'Kenya',
      sector: 'Food Security',
      date: '30 Sep 2017',
      status: 'Pending',
    },
    { id: 'CN/0190',
      name: 'Partner 0',
      project_title: 'Teaching students new language',
      cfei_id: '21/AA/2',
      agency: 'WFP',
      country: 'Spain',
      sector: 'Education',
      date: '1 Oct 2017',
      status: 'Offer Made',
    },
    { id: 'CN/603',
      name: 'Partner 0',
      project_title: 'Capacity building for small rural farmers',
      cfei_id: '123/FF2',
      agency: 'UNICEF',
      country: 'England',
      sector: 'Food Security',
      date: '30 Sep 2017',
      status: 'Offer Accepted',
    },
    { id: 'CN/0132',
      name: 'Partner 0',
      project_title: 'Capacity building for small rural farmers',
      cfei_id: '13/FA2',
      agency: 'UNICEF',
      country: 'Poland',
      sector: 'Food Security',
      date: '30 Sep 2017',
      status: 'Offer Declined',
    },
  ],
};

export default function applicationsNotesListReducer(state = initialState, action) {
  switch (action.type) {
    default:
      return state;
  }
}
