# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 12:08
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sanctioned_type', models.CharField(choices=[('Ent', 'Sanctioned Entity'), ('Ind', 'Sanctioned Individual')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('data_id', models.IntegerField(db_index=True)),
                ('listed_on', models.DateField()),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('check_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
