# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctionslist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctionedname',
            name='name',
            field=models.TextField(),
        ),
    ]
