# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctionslist', '0002_auto_20171005_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctioneditem',
            name='listed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
