# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-05 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanctionslist', '0003_auto_20180615_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanctioneditem',
            name='metadata',
        ),
    ]
