# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0024_auto_20171011_0333'),
        ('sanctionslist', '0004_auto_20171008_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionedNameMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('can_ignore', models.BooleanField(default=False)),
                ('match_type', models.CharField(choices=[('Usr', 'User Match'), ('Brd', 'Board Match'), ('Org', 'Organization Name Match')], max_length=3)),
                ('match_text', models.TextField(blank=True, null=True)),
                ('can_ignore_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='sanctionedname',
            unique_together=set([('item', 'name')]),
        ),
        migrations.AddField(
            model_name='sanctionednamematch',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='sanctionslist.SanctionedName'),
        ),
        migrations.AddField(
            model_name='sanctionednamematch',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanction_matches', to='partner.Partner'),
        ),
    ]
