# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 12:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0020_auto_20170921_0725'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('flag_type', models.CharField(choices=[('Yel', 'Yellow Flag'), ('Red', 'Red Flag')], default='Yel', max_length=3)),
                ('is_valid', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=16, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('attachment', models.FileField(upload_to=b'')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='partner.Partner')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_valid', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField()),
                ('is_cert_uploaded', models.BooleanField()),
                ('cert_uploaded_comment', models.TextField()),
                ('is_mm_consistent', models.BooleanField()),
                ('mm_consistent_comment', models.TextField()),
                ('is_indicate_results', models.BooleanField()),
                ('indicate_results_comment', models.TextField()),
                ('is_rep_risk', models.BooleanField()),
                ('rep_risk_comment', models.TextField()),
                ('is_yellow_flag', models.BooleanField()),
                ('yellow_flag_comment', models.TextField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='partner.Partner')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
