# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerflag',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
