# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20171013_0238'),
        ('review', '0003_auto_20170927_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerflag',
            name='attachment_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flag_attachments', to='common.CommonFile'),
        ),
    ]
