# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 07:38
from __future__ import unicode_literals

from django.db import migrations

def migrate_files(apps, schema_editor):
    PartnerFlag = apps.get_model('review', 'PartnerFlag')
    CommonFile = apps.get_model('common', 'CommonFile')

    for flag in PartnerFlag.objects.all():
        if flag.attachment.name:
            common_file = CommonFile.objects.create(file_field=flag.attachment)
            flag.attachment_fk = common_file
            flag.save()

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_partnerflag_attachment_fk'),
    ]

    operations = [
        migrations.RunPython(migrate_files, reverse_func),
    ]
