# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_remove_partnerflag_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerflag',
            old_name='attachment_fk',
            new_name='attachment',
        ),
    ]
