# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-25 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20171026_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerverification',
            name='can_verify',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='partnerverification',
            name='can_verify_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
