# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_auto_20171225_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerverification',
            name='is_reason_acceptable',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='partnerverification',
            name='reason_acceptable_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
