# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_auto_20180125_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerflag',
            name='flag_type',
            field=models.CharField(choices=[('Net', 'Neutral'), ('Yel', 'Yellow Flag'), ('Esc', 'Escalated Flag'), ('Red', 'Red Flag')], default='Yel', max_length=3),
        ),
    ]
