# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0014_partnerflag_sanctions_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerflag',
            name='flag_type',
            field=models.CharField(choices=[('Obs', 'Observation'), ('Yel', 'Yellow Flag'), ('Esc', 'Escalated Flag'), ('Red', 'Red Flag'), ('San', 'Sanctions List Match')], default='Yel', max_length=3),
        ),
    ]
