# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 07:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0016_partnerflag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerflag',
            name='type_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Obs', 'Observation'), ('Yel', 'Yellow Flag'), ('Esc', 'Escalated Flag'), ('Red', 'Red Flag'), ('San', 'Sanctions List Match')], default='Yel', max_length=3), default=list, size=None),
        ),
    ]
