# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 12:45
from __future__ import unicode_literals

import common.fields
import django.contrib.postgres.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0018_auto_20180625_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerflag',
            name='category',
            field=common.fields.FixedTextField(blank=True, choices=[('fraud_and_corruption', 'Fraud and corruption'), ('safeguards_violation', 'Violation of protection safeguards'), ('sex_abuse', 'Sexual exploitation and abuse'), ('terrorism_support', 'Terrorism support'), ('ZZ_other', 'Other'), ('sanctions_match', 'Sanctions List Match')], null=True),
        ),
        migrations.AlterField(
            model_name='partnerflag',
            name='flag_type',
            field=common.fields.FixedTextField(choices=[('FL1_Obs', 'Observation'), ('FL2_Yel', 'Yellow Flag'), ('FL3_Esc', 'Escalated Flag'), ('FL4_Red', 'Red Flag')], default='FL2_Yel'),
        ),
        migrations.AlterField(
            model_name='partnerflag',
            name='type_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=common.fields.FixedTextField(choices=[('FL1_Obs', 'Observation'), ('FL2_Yel', 'Yellow Flag'), ('FL3_Esc', 'Escalated Flag'), ('FL4_Red', 'Red Flag')], default='FL2_Yel'), default=list, size=None),
        ),
    ]
