# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 09:02
from __future__ import unicode_literals

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0021_auto_20180709_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerflag',
            name='category',
            field=common.fields.FixedTextField(blank=True, choices=[('C01_reputational_ethical', 'Reputational / Ethical'), ('C02_financial', 'Financial'), ('C03_operational', 'Operational'), ('C04_compliance', 'Compliance'), ('C05_sex_abuse', 'Sexual exploitation and abuse'), ('C06_safeguarding_violation', 'Safeguarding violation'), ('C99_other', 'Other'), ('sanctions_match', 'Sanctions List Match')], null=True),
        ),
    ]
