# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0022_auto_20180724_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerflag',
            name='escalation_comment',
            field=models.TextField(blank=True, max_length=5120, null=True),
        ),
    ]
