# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-30 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0023_partnerflag_escalation_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerflag',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='partnerverification',
            options={'ordering': ('-created',)},
        ),
    ]
