# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0024_auto_20180830_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerverification',
            name='can_verify',
        ),
        migrations.RemoveField(
            model_name='partnerverification',
            name='can_verify_comment',
        ),
        migrations.RemoveField(
            model_name='partnerverification',
            name='is_reason_acceptable',
        ),
        migrations.RemoveField(
            model_name='partnerverification',
            name='reason_acceptable_comment',
        ),
        migrations.AlterField(
            model_name='partnerverification',
            name='is_cert_uploaded',
            field=models.BooleanField(help_text='Has the CSO/partner uploaded its valid, non-expired registration certificate issued by the correct government body?'),
        ),
        migrations.AlterField(
            model_name='partnerverification',
            name='is_indicate_results',
            field=models.BooleanField(help_text='Does the CSO/partner have mechanisms to combat fraud and corruption, prevent sexual exploitation and abuse, and protect and safeguard beneficiaries?'),
        ),
        migrations.AlterField(
            model_name='partnerverification',
            name='is_mm_consistent',
            field=models.BooleanField(help_text='Are the mandate and mission of the CSO/partner consistent with that of the UN?'),
        ),
        migrations.AlterField(
            model_name='partnerverification',
            name='is_rep_risk',
            field=models.BooleanField(help_text='Are there any other risk-related observations associated with the CSO/partner that are not captured in UN Partner Portal, but which pose unacceptable risk to the UN?'),
        ),
        migrations.AlterField(
            model_name='partnerverification',
            name='is_yellow_flag',
            field=models.BooleanField(help_text='Do these observations pose unacceptable risk to the UN?'),
        ),
    ]
