# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 10:43
from __future__ import unicode_literals

import common.database_fields
import django.contrib.postgres.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0025_auto_20180907_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerflag',
            name='type_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=common.database_fields.FixedTextField(choices=[('FL1_Obs', 'Observation'), ('FL2_Yel', 'Yellow Flag'), ('FL3_Esc', 'Escalated Flag'), ('FL4_Red', 'Red Flag')], default='FL2_Yel'), blank=True, default=list, editable=False, null=True, size=None),
        ),
    ]
