# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 11:53
from __future__ import unicode_literals

import common.database_fields
import django.contrib.postgres.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0026_auto_20180911_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerflag',
            name='category',
            field=common.database_fields.FixedTextField(blank=True, choices=[('C01_reputational_ethical', 'Reputational / Ethical'), ('C02_financial', 'Financial'), ('C03_operational', 'Operational'), ('C04_compliance', 'Compliance'), ('C05_sex_abuse', 'Sexual exploitation and abuse'), ('C06_safeguarding_violation', 'Safeguarding violation'), ('C99_other', 'Other'), ('C90_sanctions_match', 'Sanctions Match')], null=True),
        ),
        migrations.AlterField(
            model_name='partnerflag',
            name='flag_type',
            field=common.database_fields.FixedTextField(choices=[('FL1_Obs', 'Not Risk Related'), ('FL2_Yel', 'Risk Flag'), ('FL3_Esc', 'Risk Flag Escalated to UN HQ Editor'), ('FL4_Red', 'Red Flag')], default='FL2_Yel'),
        ),
        migrations.AlterField(
            model_name='partnerflag',
            name='type_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=common.database_fields.FixedTextField(choices=[('FL1_Obs', 'Not Risk Related'), ('FL2_Yel', 'Risk Flag'), ('FL3_Esc', 'Risk Flag Escalated to UN HQ Editor'), ('FL4_Red', 'Red Flag')], default='FL2_Yel'), blank=True, default=list, editable=False, null=True, size=None),
        ),
    ]
