# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 01:22
from __future__ import unicode_literals

import common.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_auto_20170808_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('year', models.PositiveSmallIntegerField(help_text='Value in percentage, provide number from 0 to 100', validators=[common.validators.MaxCurrentYearValidator(), django.core.validators.MinValueValidator(1800)], verbose_name='Weight in percentage')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='partner.Partner')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='partnerprofile',
            name='annual_budget',
        ),
    ]
