# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 07:07
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_auto_20170814_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='country_presents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Ara', 'Arabic'), ('Chi', 'Chinese'), ('Eng', 'English'), ('Fre', 'French'), ('Rus', 'Russian'), ('Spa', 'Spanish'), ('Oth', 'Other')], max_length=2), default=list, null=True, size=None),
        ),
    ]
