# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_auto_20170814_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSelected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('summary_justification', models.TextField(blank=True, null=True)),
                ('justification_for_direct_selection', models.CharField(blank=True, choices=[('Kno', 'Known expertise'), ('Loc', 'Local presence'), ('Inn', 'Innovative approach'), ('TCC', 'Time constraints/criticality of response'), ('Imp', 'Importance of strengthening national civil society engagement'), ('Oth', 'Other')], max_length=3, null=True)),
                ('status', models.CharField(choices=[('Acc', 'Accepted'), ('Dec', 'Declined')], max_length=3)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_parnters', to='partner.Partner')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
