# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_remove_eoi_selected_partners'),
        ('partner', '0005_partnerselected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerselected',
            name='partner',
        ),
        migrations.DeleteModel(
            name='PartnerSelected',
        ),
    ]
