# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20170810_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerprofile',
            name='org_acc_system',
            field=models.CharField(choices=[('Com', 'Computerized accounting system'), ('Pap', 'Paper-based accounting system'), ('NoS', 'No accounting system')], default='NoS', max_length=3),
        ),
        migrations.DeleteModel(
            name='PartnerFinancialControlSystem',
        ),
    ]
