# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_auto_20170810_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerprofile',
            name='org_acc_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_profiles', to='partner.PartnerFinancialControlSystem'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='start_cooperate_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
