# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_auto_20170814_0407'),
        ('partner', '0009_auto_20170811_0428'),
    ]

    operations = [
    ]
