# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0010_partnerauthorisedofficer_partnerdirector'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='acronym',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
