# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 05:58
from __future__ import unicode_literals

import common.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0011_partnerprofile_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='partnership_collaborate_institution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='partnership_collaborate_institution_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='partnerbudget',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='Enter valid year.', validators=[common.validators.MaxCurrentYearValidator(), django.core.validators.MinValueValidator(1800)], verbose_name='Weight in percentage'),
        ),
        migrations.AlterField(
            model_name='partnerotherdocument',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_documents', to='partner.Partner'),
        ),
    ]
