# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0012_auto_20170831_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerauditassessment',
            name='partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='partner.Partner'),
        ),
        migrations.AlterField(
            model_name='partnerfunding',
            name='partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fund', to='partner.Partner'),
        ),
        migrations.AlterField(
            model_name='partnerheadorganization',
            name='partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_head', to='partner.Partner'),
        ),
        migrations.AlterField(
            model_name='partnermailingaddress',
            name='partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_address', to='partner.Partner'),
        ),
        migrations.AlterField(
            model_name='partnermandatemission',
            name='partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mandate_mission', to='partner.Partner'),
        ),
        migrations.AlterField(
            model_name='partnerotherinfo',
            name='partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_info', to='partner.Partner'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='partner.Partner'),
        ),
        migrations.AlterField(
            model_name='partnerreporting',
            name='partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='partner.Partner'),
        ),
    ]
