# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20170911_0323'),
        ('partner', '0013_auto_20170904_0602'),
    ]

    operations = [
    ]
