# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0014_merge_20170912_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnermember',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_members', to='partner.Partner'),
        ),
    ]
