# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 03:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0015_auto_20170912_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='country_presents',
            new_name='country_presence',
        ),
        migrations.RenameField(
            model_name='partnerprofile',
            old_name='start_cooperate_date',
            new_name='registration_date',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='partnerprofile',
            name='register_country',
        ),
        migrations.AddField(
            model_name='partner',
            name='engagement_operate_desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Briefly describe the organization's engagement with the communities in which you operate"),
        ),
        migrations.AddField(
            model_name='partner',
            name='staff_in_country',
            field=models.CharField(blank=True, choices=[('005', '1 to 50'), ('010', '51 to 100'), ('020', '101 to 200'), ('050', '201 to 500'), ('100', '501 to 1000'), ('500', '1001 to 5000'), ('Mor', 'more than 5000')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='partnerauditassessment',
            name='regular_audited_comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partnermandatemission',
            name='ethic_fraud_comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partnermandatemission',
            name='ethic_safeguard_comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='explain',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Please explain'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='gov_doc',
            field=models.FileField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='have_bank_account',
            field=models.BooleanField(default=False, verbose_name='Does the organization have a bank account?'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='have_board_directors',
            field=models.BooleanField(default=False, verbose_name='Does your organization have a board of directors?'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='have_separate_bank_account',
            field=models.BooleanField(default=False, verbose_name='Does the organization currently maintain, or has it previously maintained, a separate, interest-bearing account for UN funded projects that require a separate account?'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='registration_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='registration_to_operate_in_country',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='year_establishment',
            field=models.PositiveSmallIntegerField(default=2000, help_text='Enter valid year.', validators=[django.core.validators.MinValueValidator(1800)], verbose_name='Year of establishment'),
            preserve_default=False,
        ),
    ]
