# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 06:39
from __future__ import unicode_literals

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0016_auto_20170920_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerprofile',
            name='year_establishment',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Enter valid year.', null=True, validators=[common.validators.MaxCurrentYearValidator(), django.core.validators.MinValueValidator(1800)], verbose_name='Year of establishment'),
        ),
    ]
