# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0017_auto_20170920_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerprofile',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
