# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20170906_0127'),
        ('partner', '0018_auto_20170920_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='location_field_offices',
            field=models.ManyToManyField(related_name='location_field_offices', to='common.Point'),
        ),
        migrations.AddField(
            model_name='partner',
            name='location_of_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_of_offices', to='common.Point'),
        ),
        migrations.AddField(
            model_name='partner',
            name='more_office_in_country',
            field=models.BooleanField(default=True),
        ),
    ]
