# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0019_auto_20170921_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerbudget',
            name='budget',
            field=models.CharField(choices=[('Les', 'Less than $500,000'), ('002', '$500,001 to $2,000,000'), ('010', '$2,000,001 to $10,000,000'), ('100', '$10,000,001 to $100,000,000'), ('01m', '$100,000,001 to $1,000,000,000'), ('Mor', 'More than $1,000,000,000')], default='Les', max_length=3),
        ),
    ]
