# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0017_auto_20170922_0433'),
        ('partner', '0020_auto_20170921_0725'),
    ]

    operations = [
    ]
