# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0020_auto_20170921_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerreporting',
            name='last_report',
            field=models.DateField(blank=True, null=True, verbose_name='Date of most recent annual report'),
        ),
    ]
