# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0023_auto_20171011_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerauditassessment',
            name='assessment_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_reports', to='common.CommonFile'),
        ),
        migrations.AlterField(
            model_name='partnerauditassessment',
            name='most_recent_audit_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='most_recent_audit_reports', to='common.CommonFile'),
        ),
        migrations.AlterField(
            model_name='partnercollaborationevidence',
            name='evidence_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_evidences', to='common.CommonFile'),
        ),
        migrations.AlterField(
            model_name='partnermandatemission',
            name='ethic_fraud_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ethic_fraud_policies', to='common.CommonFile'),
        ),
        migrations.AlterField(
            model_name='partnermandatemission',
            name='ethic_safeguard_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ethic_safeguard_policies', to='common.CommonFile'),
        ),
        migrations.AlterField(
            model_name='partnermandatemission',
            name='governance_organigram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='governance_organigrams', to='common.CommonFile'),
        ),
        migrations.AlterField(
            model_name='partnerotherinfo',
            name='org_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='others_info', to='common.CommonFile'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='gov_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gov_docs', to='common.CommonFile'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='registration_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_docs', to='common.CommonFile'),
        ),
        migrations.AlterField(
            model_name='partnerreporting',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='common.CommonFile'),
        ),
    ]
