# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20171013_0238'),
        ('partner', '0025_auto_20171019_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerotherinfo',
            name='other_doc_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_info_doc_1', to='common.CommonFile'),
        ),
        migrations.AddField(
            model_name='partnerotherinfo',
            name='other_doc_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_info_doc_2', to='common.CommonFile'),
        ),
        migrations.AddField(
            model_name='partnerotherinfo',
            name='other_doc_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_info_doc_3', to='common.CommonFile'),
        ),
    ]
