# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0026_auto_20171019_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerotherdocument',
            name='partner',
        ),
        migrations.DeleteModel(
            name='PartnerOtherDocument',
        ),
    ]
