# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0027_auto_20171019_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnercollaborationevidence',
            name='date_received',
            field=models.DateField(auto_now=True, verbose_name='Date Received'),
        ),
    ]
