# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 07:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0028_auto_20171020_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerauthorisedofficer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorised_officers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerbudget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerdirector',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerexperience',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerotherinfo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerpolicyarea',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_policies', to=settings.AUTH_USER_MODEL),
        ),
    ]
