# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0029_auto_20171024_0707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerbudget',
            options={'ordering': ['partner', '-year']},
        ),
        migrations.AlterUniqueTogether(
            name='partnerbudget',
            unique_together=set([('year', 'partner')]),
        ),
    ]
