# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0029_auto_20171024_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='staff_globally',
            field=models.CharField(blank=True, choices=[('SG1', '1 to 50'), ('SG2', '51 to 100'), ('SG3', '101 to 200'), ('SG4', '201 to 500'), ('SG5', '501 to 1000'), ('SG6', '1001 to 5000'), ('SG7', 'more than 5000')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='staff_in_country',
            field=models.CharField(blank=True, choices=[('SG1', '1 to 50'), ('SG2', '51 to 100'), ('SG3', '101 to 200'), ('SG4', '201 to 500'), ('SG5', '501 to 1000'), ('SG6', '1001 to 5000'), ('SG7', 'more than 5000')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='partnerbudget',
            name='budget',
            field=models.CharField(choices=[('B01', 'Less than $500,000'), ('B02', '$500,001 to $2,000,000'), ('B03', '$2,000,001 to $10,000,000'), ('B04', '$10,000,001 to $100,000,000'), ('B05', '$100,000,001 to $1,000,000,000'), ('B06', 'More than $1,000,000,000')], default='B01', max_length=3),
        ),
        migrations.AlterField(
            model_name='partnerexperience',
            name='years',
            field=models.CharField(choices=[('YE1', 'Less than 1 year'), ('YE2', '1-5 years'), ('YE3', '5-10 years'), ('YE4', '10+ years')], default='YE1', max_length=3),
        ),
    ]
