# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_auto_20171011_0329'),
        ('partner', '0030_auto_20171027_0143'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partnercollaborationpartnership',
            unique_together=set([('partner', 'agency')]),
        ),
    ]
