# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0030_auto_20171027_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
