# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0031_partner_is_locked'),
        ('partner', '0031_auto_20171031_0715'),
    ]

    operations = [
    ]
