# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0032_merge_20171103_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerotherinfo',
            name='org_logo_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
