# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0033_partnerotherinfo_org_logo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnermailingaddress',
            name='org_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='partnerotherinfo',
            name='info_to_share',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
