# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0034_auto_20171114_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerprofile',
            name='flagged',
        ),
        migrations.AlterField(
            model_name='partner',
            name='more_office_in_country',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partnerauditassessment',
            name='capacity_assessment',
            field=models.NullBooleanField(verbose_name='Has the organization undergone a formal capacity assessment?'),
        ),
        migrations.AlterField(
            model_name='partnerauditassessment',
            name='major_accountability_issues_highlighted',
            field=models.NullBooleanField(verbose_name='Were there any major accountability issues highlighted by audits in the past three years?'),
        ),
        migrations.AlterField(
            model_name='partnerauditassessment',
            name='regular_audited',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partnerdirector',
            name='authorized',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partnerinternalcontrol',
            name='segregation_duties',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partnermandatemission',
            name='ethic_fraud',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partnermandatemission',
            name='ethic_safeguard',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partnermandatemission',
            name='partnership_with_insitutions',
            field=models.NullBooleanField(verbose_name='Has the organization collaborated with or a member of a cluster, professional netwok, consortium or any similar insitutions?'),
        ),
        migrations.AlterField(
            model_name='partnermandatemission',
            name='population_of_concern',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partnermandatemission',
            name='security_high_risk_locations',
            field=models.NullBooleanField(verbose_name='Does the organization have the ability to work in high-risk security locations?'),
        ),
        migrations.AlterField(
            model_name='partnermandatemission',
            name='security_high_risk_policy',
            field=models.NullBooleanField(verbose_name='Does the organization have policies, procedures and practices related to security risk management?'),
        ),
        migrations.AlterField(
            model_name='partnerotherinfo',
            name='confirm_data_updated',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partnerpolicyarea',
            name='document_policies',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='connectivity',
            field=models.NullBooleanField(verbose_name='Does the organization have reliable access to internet in all of its operations?'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='experienced_staff',
            field=models.NullBooleanField(verbose_name='Does the organization have an adequate number of experienced staff responsible for financial management in all operations?'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='have_authorised_officers',
            field=models.NullBooleanField(verbose_name='Does your organization have a authorised officers?'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='have_bank_account',
            field=models.NullBooleanField(verbose_name='Does the organization have a bank account?'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='have_board_directors',
            field=models.NullBooleanField(verbose_name='Does your organization have a board of directors?'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='have_feedback_mechanism',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='have_gov_doc',
            field=models.NullBooleanField(verbose_name='Does the organization have a government document?'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='have_management_approach',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='have_separate_bank_account',
            field=models.NullBooleanField(verbose_name='Does the organization currently maintain, or has it previously maintained, a separate, interest-bearing account for UN funded projects that require a separate account?'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='have_system_monitoring',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='have_system_track',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='legal_name_change',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='partnership_collaborate_institution',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='registration_to_operate_in_country',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partnerreporting',
            name='publish_annual_reports',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='partnerreview',
            name='does_recommend',
            field=models.NullBooleanField(verbose_name='Does recommend?'),
        ),
        migrations.AlterField(
            model_name='partnerreview',
            name='ethical_concerns',
            field=models.NullBooleanField(verbose_name='Ethical concerns?'),
        ),
    ]
