# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0035_auto_20171115_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerauthorisedofficer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='partnerauthorisedofficer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='partnerdirector',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='partnerdirector',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='partnerheadorganization',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='partnerheadorganization',
            name='last_name',
        ),
        migrations.AddField(
            model_name='partnerauthorisedofficer',
            name='fullname',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='partnerdirector',
            name='fullname',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='partnerheadorganization',
            name='fullname',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
