# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0036_auto_20171116_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerbudget',
            name='budget',
            field=models.CharField(blank=True, choices=[('B01', 'Less than $500,000'), ('B02', '$500,001 to $2,000,000'), ('B03', '$2,000,001 to $10,000,000'), ('B04', '$10,000,001 to $100,000,000'), ('B05', '$100,000,001 to $1,000,000,000'), ('B06', 'More than $1,000,000,000')], max_length=3, null=True),
        ),
    ]
