# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0036_auto_20171116_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerauditassessment',
            name='link_report',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partnerreporting',
            name='link_report',
            field=models.URLField(blank=True, null=True),
        ),
    ]
