# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 03:09
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0037_auto_20171123_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerauditassessment',
            name='link_report',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partnerfunding',
            name='major_donors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Ind', 'Individuals'), ('TaF', 'Trusts and foundations'), ('Pri', 'Private companies and corporations'), ('Gov', 'Government'), ('UNA', 'United Nations Agency'), ('Bil', 'Bilateral Agency/Multilateral/Development Banks'), ('NGO', 'International Non Governmental Organizations'), ('Oth', 'Other')], max_length=3), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='partnerreporting',
            name='link_report',
            field=models.URLField(blank=True, null=True),
        ),
    ]
