# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0038_auto_20171123_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerdirector',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnerdirector',
            name='fax',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnerdirector',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
