# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0039_auto_20171212_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='any_accreditation',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='any_partnered_with_un',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='any_reference',
            field=models.NullBooleanField(),
        ),
    ]
