# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20171031_0715'),
        ('partner', '0040_auto_20171212_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerAuditReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('org_audit', models.CharField(choices=[('Int', 'Internal audit'), ('Fin', 'Financial statement audit'), ('Don', 'Donor audit')], max_length=3)),
                ('link_report', models.URLField(blank=True, null=True)),
                ('audit_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_reports', to='partner.PartnerAuditAssessment')),
                ('most_recent_audit_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_audit_reports', to='common.CommonFile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='partner',
            name='staff_globally',
            field=models.CharField(blank=True, choices=[('SG1', '1 to 10'), ('SG2', '11 to 25'), ('SG3', '26 to 50'), ('SG4', '51 to 100'), ('SG5', '101 to 250'), ('SG6', '251 to 500'), ('SG7', 'more than 500')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='staff_in_country',
            field=models.CharField(blank=True, choices=[('SG1', '1 to 10'), ('SG2', '11 to 25'), ('SG3', '26 to 50'), ('SG4', '51 to 100'), ('SG5', '101 to 250'), ('SG6', '251 to 500'), ('SG7', 'more than 500')], max_length=3, null=True),
        ),
    ]
