# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-27 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0040_auto_20171212_0703'),
        # TODO: Change to the following after optional fields are merged
        # ('partner', '0044_auto_20171227_1426.py'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnercollaborationpartnership',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='partnerfunding',
            name='main_donors_list',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Please list your main donors'),
        ),
        migrations.AlterField(
            model_name='partnerfunding',
            name='source_core_funding',
            field=models.CharField(max_length=5000, verbose_name='Please state your source(s) of core funding'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='connectivity_excuse',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='partnership_collaborate_institution_desc',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
