# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 13:05
from __future__ import unicode_literals

from django.db import migrations


def move_audit_report_field_to_separate_model(apps, schema_editor):
    PartnerAuditAssessment = apps.get_model('partner', 'PartnerAuditAssessment')
    PartnerAuditReport = apps.get_model('partner', 'PartnerAuditReport')

    for audit in PartnerAuditAssessment.objects.all():
        if audit.org_audits:
            PartnerAuditReport.objects.create(
                partner=audit.partner,
                org_audit=audit.org_audits[0],
                most_recent_audit_report=audit.most_recent_audit_report,
                link_report=audit.link_report,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0041_auto_20171220_1302'),
    ]

    operations = [
        migrations.RunPython(move_audit_report_field_to_separate_model),
    ]
