# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-27 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0043_auto_20171220_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerauditreport',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='partnerauditreport',
            name='org_audit',
            field=models.CharField(blank=True, choices=[('Int', 'Internal audit'), ('Fin', 'Financial statement audit'), ('Don', 'Donor audit')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='partnerexperience',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_experiences', to='common.Specialization'),
        ),
        migrations.AlterField(
            model_name='partnerexperience',
            name='years',
            field=models.CharField(blank=True, choices=[('YE1', 'Less than 1 year'), ('YE2', '1-5 years'), ('YE3', '5-10 years'), ('YE4', '10+ years')], max_length=3, null=True),
        ),
    ]
