# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-28 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0044_auto_20171227_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnercollaborationevidence',
            name='date_received',
            field=models.DateField(null=True, verbose_name='Date Received'),
        ),
        migrations.AlterField(
            model_name='partnercollaborationevidence',
            name='mode',
            field=models.CharField(blank=True, choices=[('Acc', 'Accreditation'), ('Ref', 'Reference')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='partnercollaborationevidence',
            name='organization_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
