# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-28 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0045_auto_20171228_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnercollaborationpartnership',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaborations_partnership', to='agency.Agency'),
        ),
    ]
