# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0049_auto_20180108_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerauditassessment',
            name='comment',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='partnerauditassessment',
            name='regular_audited_comment',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='partnerinternalcontrol',
            name='comment',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='partnermandatemission',
            name='background_and_rationale',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='partnermandatemission',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Please state which cluster, network or consortium and briefly explain the collaboration professional netwok, consortium or any similar insitutions?'),
        ),
        migrations.AlterField(
            model_name='partnermandatemission',
            name='ethic_fraud_comment',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='partnermandatemission',
            name='ethic_safeguard_comment',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='partnermandatemission',
            name='governance_hq',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Briefly describe the headquarters oversight of country/branch office operations including any reporting requirements of the country/branch office to HQ'),
        ),
        migrations.AlterField(
            model_name='partnermandatemission',
            name='governance_structure',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name="Briefly describe the organization's governance structure"),
        ),
        migrations.AlterField(
            model_name='partnermandatemission',
            name='mandate_and_mission',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='partnermandatemission',
            name='security_desc',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name="Briefly describe the organization's ability, if any, to scale-up operations in emergencies or other situations requiring rapid response."),
        ),
        migrations.AlterField(
            model_name='partnerotherinfo',
            name='info_to_share',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='experienced_staff_desc',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='explain',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Please explain'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='feedback_mechanism_desc',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='financial_control_system_desc',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='management_approach_desc',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='registration_comment',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='system_monitoring_desc',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='partnerreporting',
            name='key_result',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
