# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 05:40
from __future__ import unicode_literals

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0049_auto_20180108_0321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerbudget',
            options={'ordering': ['-year', 'id']},
        ),
        migrations.AlterField(
            model_name='partnerbudget',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='Enter valid year.', validators=[common.validators.MaxCurrentYearValidator(), django.core.validators.MinValueValidator(1800)]),
        ),
        migrations.AlterUniqueTogether(
            name='partnerbudget',
            unique_together=set([('partner', 'year')]),
        ),
    ]
