# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0051_merge_20180115_1050'),
    ]

    operations = [
    ]
