# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0054_partnerauditassessment_regular_capacity_assessments'),
        ('partner', '0053_auto_20180123_1114'),
    ]

    operations = [
    ]
