# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-07 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0056_auto_20180129_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerotherinfo',
            name='org_logo_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
