# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-14 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0057_auto_20180507_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerreview',
            old_name='peformance_financial',
            new_name='performance_financial',
        ),
    ]
