# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-15 09:04
from __future__ import unicode_literals

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0058_auto_20180514_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnermember',
            name='role',
            field=common.fields.FixedTextField(choices=[('HQ_ADMIN', 'HQ Administrator'), ('HQ_EDITOR', 'HQ Editor'), ('HQ_READER', 'HQ Reader'), ('ADMIN', 'Administrator'), ('EDITOR', 'Editor'), ('READER', 'Reader')], default='READER'),
        ),
    ]
