# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0061_remove_partnermember_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='display_type',
            field=models.CharField(choices=[('CBO', 'Community Based Organization (CBO) '), ('NGO', 'National NGO'), ('Int', 'International NGO (INGO)'), ('Aca', 'Academic Institution'), ('RCC', 'Red Cross/Red Crescent Movement')], max_length=3, verbose_name='Organization Type'),
        ),
    ]
