# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0062_auto_20180608_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnermandatemission',
            name='partnership_with_insitutions',
        ),
        migrations.AddField(
            model_name='partnermandatemission',
            name='partnership_with_institutions',
            field=models.NullBooleanField(verbose_name='Has the organization collaborated with or a member of a cluster, professional network, consortium or any similar institutions?'),
        ),
    ]
