# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0063_auto_20180612_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Locked and Marked for Deletion'),
        ),
    ]
