# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-13 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0064_auto_20180620_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='partnerauditassessment',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='partnerauditreport',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='partnerauthorisedofficer',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='partnercapacityassessment',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='partnercollaborationevidence',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='partnercollaborationpartnership',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='partnerdirector',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='partnerexperience',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='partnerfunding',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='partnerheadorganization',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='partnerinternalcontrol',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='partnermailingaddress',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='partnermandatemission',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='partnermember',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='partnerotherinfo',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='partnerpolicyarea',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='partnerprofile',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='partnerreporting',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='partnerreview',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='partnermandatemission',
            name='description',
        ),
        migrations.RemoveField(
            model_name='partnermandatemission',
            name='partnership_with_institutions',
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='partnership_collaborate_institution',
            field=models.NullBooleanField(verbose_name='Has the organization collaborated with or a member of a cluster, professional network, consortium or any similar institutions?'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='partnership_collaborate_institution_desc',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Please state which cluster, network or consortium and briefly explain the collaboration professional network, consortium or any similar institutions?'),
        ),
    ]
