# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 12:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0066_auto_20180724_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerauthorisedofficer',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnerdirector',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnerheadorganization',
            name='authorized',
            field=models.NullBooleanField(verbose_name='Is Authorised Officer?'),
        ),
        migrations.AddField(
            model_name='partnerheadorganization',
            name='board_member',
            field=models.NullBooleanField(verbose_name='Is Board Member?'),
        ),
        migrations.AddField(
            model_name='partnerheadorganization',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partnerauthorisedofficer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partnerdirector',
            name='authorized',
            field=models.NullBooleanField(verbose_name='Is Authorised Officer?'),
        ),
        migrations.AlterField(
            model_name='partnerdirector',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partnerheadorganization',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_heads', to='partner.Partner'),
        ),
    ]
