# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0066_auto_20180724_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnermandatemission',
            name='ethic_fraud',
            field=models.NullBooleanField(verbose_name='Does the organization have a policy or code of conduct to safeguard against fraud and corruption?'),
        ),
        migrations.AlterField(
            model_name='partnermandatemission',
            name='ethic_fraud_comment',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Briefly describe the organization’s mechanisms to safeguard against fraud, corruption and other unethical behaviour.'),
        ),
        migrations.AlterField(
            model_name='partnermandatemission',
            name='ethic_safeguard',
            field=models.NullBooleanField(verbose_name='Does the organization have a policy or code of conduct to safeguard against the violation and abuse of beneficiaries?'),
        ),
        migrations.AlterField(
            model_name='partnermandatemission',
            name='ethic_safeguard_comment',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Briefly describe the organization’s mechanisms to safeguard against the violation and abuse of beneficiaries, including sexual exploitation and abuse.'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='any_accreditation',
            field=models.NullBooleanField(verbose_name='Would you like to upload any accreditations received by your organization?'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='any_reference',
            field=models.NullBooleanField(verbose_name='Would you like to upload any reference letters for your organization?'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='have_authorised_officers',
            field=models.NullBooleanField(verbose_name='Does your organization have any other authorized officers who are not listed above?'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='have_board_directors',
            field=models.NullBooleanField(verbose_name='Does your organization have a board of director(s)?'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='have_management_approach',
            field=models.NullBooleanField(verbose_name='Does the organization use a results-based approach to managing programmes and projects?'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='have_system_monitoring',
            field=models.NullBooleanField(verbose_name='Does your organization have a system for monitoring and evaluating its programmes and projects?'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='have_system_track',
            field=models.NullBooleanField(verbose_name='Does your organization have a system to track expenditures, prepare project reports, and prepare claims for donors?'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='partnership_collaborate_institution_desc',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Please state which cluster, network or consortium and briefly explain the collaboration'),
        ),
    ]
