# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20180724_0902'),
        ('partner', '0066_auto_20180724_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerGoverningDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('editable', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governing_documents', to='common.CommonFile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerRegistrationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('registration_number', models.TextField(blank=True, max_length=255, null=True)),
                ('editable', models.BooleanField(default=False)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_documents', to='common.CommonFile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='partnerprofile',
            old_name='have_gov_doc',
            new_name='have_governing_document',
        ),
        migrations.RenameField(
            model_name='partnerprofile',
            old_name='registration_comment',
            new_name='missing_registration_document_comment',
        ),
        migrations.RenameField(
            model_name='partnerprofile',
            old_name='registration_to_operate_in_country',
            new_name='registered_to_operate_in_country',
        ),
        migrations.RemoveField(
            model_name='partnerprofile',
            name='gov_doc',
        ),
        migrations.RemoveField(
            model_name='partnerprofile',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='partnerprofile',
            name='registration_doc',
        ),
        migrations.RemoveField(
            model_name='partnerprofile',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='missing_governing_document_comment',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='partnerregistrationdocument',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_documents', to='partner.PartnerProfile'),
        ),
        migrations.AddField(
            model_name='partnergoverningdocument',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governing_documents', to='partner.PartnerProfile'),
        ),
    ]
