# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 06:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0067_auto_20180726_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnergoverningdocument',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='partnerregistrationdocument',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='partnergoverningdocument',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='governing_documents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerregistrationdocument',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registration_documents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
