# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0069_auto_20180803_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerregistrationdocument',
            name='issuing_authority',
            field=models.TextField(default='DEFAULT ISSUER'),
            preserve_default=False,
        ),
    ]
