# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0071_auto_20180807_1010'),
        ('partner', '0067_auto_20180731_1209'),
    ]

    operations = [
    ]
