# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-13 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0072_merge_20180808_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnercollaborationevidence',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
