# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-03 13:02
from __future__ import unicode_literals

import common.database_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0073_partnercollaborationevidence_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='migrated_from',
            field=common.database_fields.FixedTextField(
                blank=True, choices=[('UNHCR', 'UNHCR Database')], null=True, editable=False
            ),
        ),
        migrations.AddField(
            model_name='partner',
            name='migrated_original_id',
            field=models.PositiveIntegerField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='migrated_timestamp',
            field=models.DateTimeField(blank=True, null=True, editable=False),
        ),
    ]
