# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0078_auto_20180926_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='partnerprofile',
            options={'ordering': ('-created',)},
        ),
    ]
