# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0079_auto_20180927_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnermandatemission',
            name='ethic_safeguard',
            field=models.NullBooleanField(verbose_name='Are these mechanisms formally documented in an organizational policy or code of conduct?'),
        ),
    ]
