# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0080_auto_20181008_0845'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partner',
            unique_together=set([('legal_name', 'country_code')]),
        ),
    ]
