# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-26 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0082_auto_20181019_0933'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partnerinternalcontrol',
            unique_together=set([('partner', 'functional_responsibility')]),
        ),
        migrations.AlterUniqueTogether(
            name='partnerpolicyarea',
            unique_together=set([('partner', 'area')]),
        ),
    ]
