# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0084_auto_20181029_0935'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partner',
            unique_together=set([('legal_name', 'country_code', 'hq')]),
        ),
    ]
