# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0085_auto_20181106_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerreporting',
            name='link_report',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
