# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-15 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0088_auto_20181113_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerotherinfo',
            name='org_logo_thumbnail',
        ),
    ]
