# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0089_remove_partnerotherinfo_org_logo_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='legal_name_length',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
