# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0090_partner_legal_name_length'),
    ]

    operations = [
        migrations.RunSQL("""
        CREATE OR REPLACE FUNCTION fill_legal_name_length()
        RETURNS trigger AS
        $BODY$
        BEGIN
            NEW.legal_name_length := length(NEW.legal_name);
        RETURN NEW;
        END;
        $BODY$
        LANGUAGE plpgsql;
        """),
        migrations.RunSQL("DROP TRIGGER IF EXISTS fill_legal_name_length on partner_partner;"),
        migrations.RunSQL("""
        CREATE TRIGGER fill_legal_name_length
        BEFORE INSERT OR UPDATE OF legal_name ON partner_partner
        FOR EACH ROW EXECUTE PROCEDURE fill_legal_name_length();
        """),
        migrations.RunSQL("UPDATE partner_partner SET legal_name_length = length(legal_name);"),
    ]
