# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 09:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0091_legal_name_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='legal_name',
            field=models.TextField(db_index=True, max_length=255, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='legal_name_length',
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
    ]
