# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-04 08:32
from __future__ import unicode_literals

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0094_auto_20181203_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerbudget',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='Enter valid year.', validators=[common.validators.max_current_year_validator, django.core.validators.MinValueValidator(1800)]),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='year_establishment',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Enter valid year.', null=True, validators=[common.validators.max_current_year_validator, django.core.validators.MinValueValidator(1800)], verbose_name='Year of establishment'),
        ),
        migrations.AlterField(
            model_name='partnerregistrationdocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, validators=[common.validators.future_date_validator]),
        ),
        migrations.AlterField(
            model_name='partnerregistrationdocument',
            name='issue_date',
            field=models.DateField(validators=[common.validators.past_date_validator]),
        ),
    ]
