# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0095_auto_20190104_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='display_type',
            field=models.CharField(choices=[('CBO', 'Community Based Organization (CBO)'), ('NGO', 'National NGO'), ('Int', 'International Civil Society Organization'), ('Aca', 'Academic Institution'), ('RCC', 'Red Cross/Red Crescent National Society')], max_length=3, verbose_name='Organization Type'),
        ),
    ]
