# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-12 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0096_auto_20190311_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('legal_name', 'country_code')},
        ),
    ]
